#!/bin/bash

if ! gcloud config get account | grep vmware >/dev/null 2>&1; then
    gcloud auth login
fi

if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${:-runtime-networking}"
    
export GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY=$(gcloud secrets versions access --secret gcp-tas-runtime-service-account latest | yq .config-json)


PACKAGE_NAME="golang-1.21-linux" fly -t "${FLY_TARGET}" e -c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/bosh-vendor-package/linux.yml \
-i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci \
-i repo=${WORKSPACE_ROOT}/routing-release \
-i package-release=${WORKSPACE_ROOT}/golang-release \
--inputs-from routing-release/template-tests \
--image image \
--include-ignored \
-o "vendored-repo=${WORKSPACE_ROOT}/outputs/vendored-repo"
