#!/bin/bash

if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${:-runtime-networking}"

DEBUG="true" RELEASE="routing" fly -t "${FLY_TARGET}" e -c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/bosh-export-release/linux.yml \
-i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci \
-i repo=${WORKSPACE_ROOT}/routing-release \
-i toolsmiths-env=${WORKSPACE_ROOT}/envs/${TOOLSMITHS_ENVIRONMENT_NAME} \
--inputs-from routing-release/template-tests \
--image image 
