#!/bin/bash

if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${:-runtime-networking}"

DEBUG="true" MANIFEST="ci/routing-release/manifests/cipher.yml" ENVS='DEPLOYMENT_NAME=cipher
DEPLOYMENT_RELEASE_DIR=$(echo $PWD/release-01)
DEPLOYMENT_GOROUTER_IP=$(bosh -d cf vms --json | jq -r ".Tables[].Rows[] | select(.instance | startswith(\"router\")) | .ips" | head -n1)'  fly -t "${FLY_TARGET}" e -c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/bosh-deploy-manifest/linux.yml \
-i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci \
-i repo=${WORKSPACE_ROOT}/routing-release \
-i release-01=${WORKSPACE_ROOT}/cipher-test-release \
-i toolsmiths-env=${WORKSPACE_ROOT}/envs/${TOOLSMITHS_ENVIRONMENT_NAME} \
--inputs-from routing-release/template-tests \
--image image
