#!/bin/bash

if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${:-runtime-networking}"

DEBUG=true DEFAULT_PARAMS="ci/routing-release/default-params/build-binaries/linux.yml" FUNCTIONS="ci/routing-release/helpers/build-binaries.h" fly -t "${FLY_TARGET}" e -c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/build-binaries/linux.yml -i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci -i repo=${WORKSPACE_ROOT}/routing-release --inputs-from routing-release/template-tests --image image -o built-binaries=${WORKSPACE_ROOT}/binaries
