#!/bin/bash

if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${:-runtime-networking}"

DEBUG="true" fly -t "${FLY_TARGET}" e -c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/build-release-notes/linux.yml \
-i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci \
-i repo=${WORKSPACE_ROOT}/routing-release \
-i version=${WORKSPACE_ROOT}/version \
-i previous-github-release=${WORKSPACE_ROOT}/previous-github-release \
-o built-release-notes=${WORKSPACE_ROOT}/outputs/built-release-notes \
--inputs-from routing-release/template-tests \
--image image  \
--include-ignored
