#!/bin/bash

if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${:-runtime-networking}"

CONFIGS="${1}" fly -t "${FLY_TARGET}" e -c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/create-acceptance-test-configs/linux.yml \
-i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci \
-i cf-deployment-concourse-tasks=${WORKSPACE_ROOT}/cf-deployment-concourse-tasks \
-i toolsmiths-env=${WORKSPACE_ROOT}/envs/${TOOLSMITHS_ENVIRONMENT_NAME} \
-o created-acceptance-test-configs=${WORKSPACE_ROOT}/outputs/created-acceptance-test-configs \
--inputs-from routing-release/template-tests \
--image image 
