#!/bin/bash

if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${FLY_TARGET:-runtime-networking}"

fly -t "${FLY_TARGET}" e -c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/lint-ci/linux.yml \
-i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci \
--inputs-from new-routing-release/template-tests \
--image image
