#!/bin/bash

if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${:-runtime-networking}"

FUNCTIONS="ci/winc-release/helpers/configure-binaries.ps1" ENVS="WINC_TEST_ROOTFS=docker:///cloudfoundry/windows2016fs:2019" \
DIR=src/code.cloudfoundry.org/winc \
fly -t "${FLY_TARGET}" e \
-c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/run-bin-test/windows.yml \
-i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci \
-i repo=${WORKSPACE_ROOT}/winc-release \
-i built-binaries=${WORKSPACE_ROOT}/binaries \
--image image
