#!/bin/bash
G
if [[ -z ${WORKSPACE_ROOT} ]]; then
    WORKSPACE_ROOT="${HOME}/workspace"
fi
FLY_TARGET="${:-runtime-networking}"

DEBUG=true \
ENVS='ISO_SEG_NAME=persistent_isolation_segment ISO_SEG_DOMAIN_PREFIX=iso-seg ENABLE_ISOLATION_SEGMENT_TESTS=true ENABLE_DYNAMIC_ASG_TESTS=true' \
FUNCTIONS="ci/routing-release/helpers/configure-binaries.bash" \
fly -t "${FLY_TARGET}" e \
-c ${WORKSPACE_ROOT}/wg-app-platform-runtime-ci/shared/tasks/run-bin-test/linux.yml \
-i ci=${WORKSPACE_ROOT}/wg-app-platform-runtime-ci \
-i repo=${WORKSPACE_ROOT}/routing-release \
--inputs-from routing-release/template-tests \
--image image
