---
jobs:
- name: garden-rootfs
  serial: true
  plan:
  - in_parallel:
    - get: http-golang-download
      trigger: true
    - get: garden-rootfs-repo
      trigger: true
    - get: ci
    - get: image
  - task: build-garden-rootfs
    privileged: true
    output_mapping:
      image: garden-rootfs
    config:
      platform: linux
      run:
        path: build
      params:
        CONTEXT: garden-rootfs-repo/garden-runc-release/dockerfiles/garden-rootfs
        OUTPUT_OCI: true
        IMAGE_PLATFORM: linux/amd64,linux/arm64
      inputs:
        - name: garden-rootfs-repo
      outputs:
        - name: image
      image_resource:
        type: registry-image
        source:
          repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/concourse/oci-build-task
          username: _json_key
          password: ((gcp-wg-arp-service-account/config-json))
  - put: garden-rootfs
    params:
      image: garden-rootfs/image
      bump_aliases: true
  - task: validate-label-urls
    file: ci/shared/tasks/lint-docker-image/linux.yml
    image: image
    input_mapping:
      docker-image: garden-rootfs
- name: garden-fuse
  serial: true
  plan:
  - in_parallel:
    - get: http-golang-download
      trigger: true
    - get: garden-fuse-repo
      trigger: true
    - get: ci
    - get: image
  - task: build-garden-fuse
    privileged: true
    output_mapping:
      image: garden-fuse
    config:
      platform: linux
      run:
        path: build
      params:
        CONTEXT: garden-fuse-repo/garden-runc-release/dockerfiles/garden-fuse
        OUTPUT_OCI: true
        IMAGE_PLATFORM: linux/amd64,linux/arm64
      inputs:
        - name: garden-fuse-repo
      outputs:
        - name: image
      image_resource:
        type: registry-image
        source:
          repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/concourse/oci-build-task
          username: _json_key
          password: ((gcp-wg-arp-service-account/config-json))
  - put: garden-fuse
    params:
      image: garden-fuse/image
      bump_aliases: true
  - task: validate-label-urls
    file: ci/shared/tasks/lint-docker-image/linux.yml
    image: image
    input_mapping:
      docker-image: garden-fuse

resources:
- name: garden-rootfs
  type: registry-image
  icon: docker
  source:
    username: ((dockerhub-appruntimeplatform-username))
    password: ((dockerhub-appruntimeplatform-password))
    repository: cloudfoundry/garden-rootfs
    tag: latest

- name: garden-fuse
  type: registry-image
  icon: docker
  source:
    username: ((dockerhub-appruntimeplatform-username))
    password: ((dockerhub-appruntimeplatform-password))
    repository: cloudfoundry/garden-fuse
    tag: latest

- name: garden-rootfs-repo
  type: git
  icon: source-branch
  source:
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci.git
    branch: main
    private_key: ((github-appruntimeplatform-bot/private-key))
    paths:
    - garden-runc-release/dockerfiles/garden-rootfs

- name: garden-fuse-repo
  type: git
  icon: source-branch
  source:
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci.git
    branch: main
    private_key: ((github-appruntimeplatform-bot/private-key))
    paths:
    - garden-runc-release/dockerfiles/garden-fuse

- name: ci
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci

- name: image
  type: registry-image
  icon: docker
  source:
    repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/cloudfoundry/tas-runtime-build
    username: _json_key
    password: ((gcp-wg-arp-service-account/config-json))

- name: http-golang-download
  type: command-runner
  icon: link-variant
  source:
    version_key: "latest-golang"
    check_command: "echo https://dl.google.com/go/$(curl -s https://go.dev/dl/?mode=json | grep -o 'go.*.linux-amd64.tar.gz' | head -n 1 | tr -d '\r\n')"
    in_command:    "curl --silent --fail --output $1/golang.tgz https://dl.google.com/go/$(curl -s https://go.dev/dl/?mode=json | grep -o 'go.*.linux-amd64.tar.gz' | head -n 1 | tr -d '\r\n')"

resource_types:
- name: command-runner
  type: docker-image
  source:
    repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/cloudfoundrydevelopers/command-runner-resource
    username: _json_key
    password: ((gcp-wg-arp-service-account/config-json))
    tag: latest

