#!/bin/bash
set -o errexit
set -o pipefail

: ${ADMIN_PASSWORD:?"!"}
: ${ADMIN_USER:?"!"}
: ${API:?"!"}
: ${APPS_DOMAIN:?"!"}
: ${UNALLOCATED_IP:?"!"}
: ${WINDOWS_STACK:?"!"}

: ${CREDHUB_MODE:=""}
: ${CREDHUB_CLIENT:="credhub_admin_client"}
: ${CREDHUB_SECRET:=""}

if [ ! -z "$CREDHUB_MODE" ]; then
  set -e
  if ! command -v credhub > /dev/null 2>&1; then
    # TODO add credhub binary to the ci docker image
    credhub_cli_version=2.9.10
    wget https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/${credhub_cli_version}/credhub-linux-${credhub_cli_version}.tgz -P /tmp
    tar xzvf /tmp/credhub-linux-${credhub_cli_version}.tgz -C /usr/local/bin
    chmod +x /usr/local/bin/credhub
  fi

  pushd "bbl-state/${ENVIRONMENT}"
    CREDHUB_SECRET=$(
      eval "$(bbl print-env)"
      cf_credhub_secret=$(credhub get -n /bosh-${ENVIRONMENT}/cf/credhub_admin_client_secret -j | jq -r .value)
      echo $cf_credhub_secret
      )
  popd
  set +e
fi

read -r -d '' JSON_TEMPLATE <<EOF || true
{
  "api": "$API",
  "apps_domain": "$APPS_DOMAIN",
  "admin_user": "$ADMIN_USER",
  "admin_password": "$ADMIN_PASSWORD",
  "skip_ssl_validation": true,
  "include_apps": false,
  "include_detect": false,
  "include_persistent_app": false,
  "include_routing": false,
  "include_v3": false,
  "include_capi_no_bridge": false,
  "include_security_groups": true,
  "use_http": true,
  "include_windows": true,
  "include_ssh": true,
  "credhub_mode": "$CREDHUB_MODE",
  "credhub_client": "$CREDHUB_CLIENT",
  "credhub_secret": "$CREDHUB_SECRET",
  "cf_push_timeout": 300,
  "unallocated_ip_for_security_group": "$UNALLOCATED_IP",
  "use_windows_test_task": true,
  "use_windows_context_path": true,
  "windows_stack": "$WINDOWS_STACK"
}
EOF

echo "$JSON_TEMPLATE" > integration-config/integration_config.json
