---
platform: linux

inputs:
- name: repo
- name: ci
- name: go-version

outputs:
- name: bumped-repo

params:
  GO_VERSION_FILE: go-version/go-version.json
  PLATFORM:
  PREFIX: ""

run:
  path: ci/shared/tasks/bump-golang-package-name/task.bash
