---
platform: linux

inputs:
- name: ci
- name: env

outputs:
- name: built-acceptance-test-configs

params:
  BBL_STATE_DIR:
  CONFIGS:
  DIR: .
  ENVS:
  WITH_ISOSEG: false
  WITH_ROUTING_ISOSEG:
  WITH_TCP_ISOSEG:
  WITH_DYNAMIC_ASG: false
  CREDHUB_MODE: assisted
  WITH_HTTP2: false
  WITH_COMMA_DELIMITED_ASG_DESTINATIONS: false
  WITH_VOLUME_SERVICES: false
  ISOSEG_NAME: persistent_isolation_segment
  ISOSEG_DOMAIN:
  ISOSEG_DOMAIN_SUFFIX:
  WITH_APPS: true
  WITH_CONTAINER_NETWORKING: true
  WITH_DETECT: true
  WITH_DEPLOYMENTS: true
  WITH_DOCKER: true
  WITH_INTERNET_DEPENDENT: true
  WITH_ROUTE_SERVICES: true
  WITH_ROUTING: true
  WITH_SECURITY_GROUPS: true
  WITH_SERVICES: true
  WITH_SERVICE_DISCOVERY: true
  WITH_SERVICE_INSTANCE_SHARING: true
  WITH_SSH: true
  WITH_SSO: true
  WITH_TASKS: true
  WITH_TCP_ROUTING: true
  WITH_USER_PROVIDED_SERVICES: true
  WITH_V3: true
  WITH_ZIPKIN: true


run:
  path: ci/shared/tasks/build-acceptance-test-configs/task.bash
