FROM mcr.microsoft.com/windows/servercore:1809

LABEL org.cloudfoundry.groot-windows-test-servercore.dockerfile.url="https://github.com/cloudfoundry/wg-app-platform-runtime-ci/blob/main/winc-release/dockerfiles/servercore/Dockerfile"
LABEL org.cloudfoundry.groot-windows-test-servercore.notes.md="Used by winc-release \
"

RUN mkdir C:\temp\test & echo hello > C:\temp\test\hello
