#!/usr/bin/env bash

set -euo pipefail
GOPATH="$PWD/diego-release"
mkdir -p "$GOPATH/bin"
PATH="$PATH:$GOPATH/bin"

DIEGO_GARDEN_SUBMODULE=src/garden
DIEGO_GUARDIAN_SUBMODULE=src/guardian
DIEGO_IDMAPPER_SUBMODULE=src/idmapper
DIEGO_GROOTFS_SUBMODULE=src/grootfs

GARDEN_RUNC_GARDEN_SUBMODULE=src/garden
GARDEN_RUNC_GUARDIAN_SUBMODULE=src/guardian
GARDEN_RUNC_IDMAPPER_SUBMODULE=src/idmapper
GARDEN_RUNC_GROOTFS_SUBMODULE=src/grootfs

sha="$(cat garden-runc-release-github-release/commit_sha)"
git -C garden-runc-release-master checkout "$sha"
git -C garden-runc-release-master submodule update --init --recursive

GARDEN_SHA=$(git -C garden-runc-release-master ls-tree HEAD $GARDEN_RUNC_GARDEN_SUBMODULE | awk '{print $3}')
GUARDIAN_SHA=$(git -C garden-runc-release-master ls-tree HEAD $GARDEN_RUNC_GUARDIAN_SUBMODULE | awk '{print $3}')
IDMAPPER_SHA=$(git -C garden-runc-release-master ls-tree HEAD $GARDEN_RUNC_IDMAPPER_SUBMODULE | awk '{print $3}')
GROOTFS_SHA=$(git -C garden-runc-release-master ls-tree HEAD $GARDEN_RUNC_GROOTFS_SUBMODULE | awk '{print $3}')

git -C "diego-release/$DIEGO_GARDEN_SUBMODULE" fetch --all
git -C "diego-release/$DIEGO_GARDEN_SUBMODULE" reset --hard "$GARDEN_SHA"

git -C "diego-release/$DIEGO_GUARDIAN_SUBMODULE" fetch --all
git -C "diego-release/$DIEGO_GUARDIAN_SUBMODULE" reset --hard "$GUARDIAN_SHA"

git -C "diego-release/$DIEGO_IDMAPPER_SUBMODULE" fetch --all
git -C "diego-release/$DIEGO_IDMAPPER_SUBMODULE" reset --hard "$IDMAPPER_SHA"

git -C "diego-release/$DIEGO_GROOTFS_SUBMODULE" fetch --all
git -C "diego-release/$DIEGO_GROOTFS_SUBMODULE" reset --hard "$GROOTFS_SHA"


pushd diego-release
  ./scripts/sync-package-specs
  ./scripts/sync-submodule-config

  if [ -n "$(git status --porcelain)" ]; then
    git config user.email "cf-diego+github@pivotal.io"
    git config user.name "CI (Automated)"
    git add -A .
    git commit -m "Update garden, guardian, idmapper, and grootfs submodules"
  fi
popd

cp -r diego-release/. bumped-diego-release
