#!/bin/bash

set -e -x

WORKDIR=$PWD

TAG=$(cat routing-release-tarball/version)

# switch release repo to tag determined by tarball version
pushd routing-release-master
  git fetch --tags
  git checkout $TAG
  git submodule update --init --recursive
popd

cp -r routing-release-master/. routing-release
