#!/bin/bash

echo "Checking expired certs in $CERT_DIRECTORY"

expired_certs=$(find $CERT_DIRECTORY -name *.crt | xargs -n1 -I{} ./diego-ci/tasks/check_cert_expired.rb {} 60)
if [ ! -z "$expired_certs" ]; then
  echo "Found certs expiring in 60 days:"
  echo "$expired_certs"
  exit 1
fi
