#!/usr/bin/env bash

set -ex

export GOPATH=${PWD}/diego-release
export PATH=${PATH}:${GOPATH}/bin

pushd ${GOPATH}
  ./scripts/sync-package-specs

  if ! git diff-files --exit-code --ignore-submodules; then
    echo >&2 "There are unstaged changes in the index! Be sure to run 'sync-package-specs' and commit those changes."
    exit 1
  fi

  if ! git diff-index --cached --exit-code HEAD --ignore-submodules; then
    echo >&2 "There are uncommitted changes in the index! Be sure to run 'sync-package-specs' and commit those changes."
    exit 1
  fi
popd


pushd ${GOPATH}
  ./scripts/sync-submodule-config

  if ! git diff-files --exit-code --ignore-submodules; then
    echo >&2 "There are unstaged changes in the index! Be sure to run 'sync-submodule-config' and commit those changes."
    exit 1
  fi

  if ! git diff-index --cached --exit-code HEAD --ignore-submodules; then
    echo >&2 "There are uncommitted changes in the index! Be sure to run 'sync-submodule-config' and commit those changes."
    exit 1
  fi
popd

pushd ${GOPATH}
  ./scripts/staticcheck
popd
