#!/bin/bash

set -e -x -u

cd diego-release

git config user.email "cf-diego@pivotal.io"
git config user.name "CI (Automated)"

issue_file=$(mktemp)

cat > ${issue_file} <<EOF
${TITLE}

${DESCRIPTION}
EOF

hub issue create -F ${issue_file} -l ${LABEL} > ../issue-file/link
