#!/bin/bash

set -e -x -u

version=`cat version/number`
tarball_name=diego-$version.tgz

pushd diego-release
  bosh -n create-release --tarball=$tarball_name --version $version --force --sha2

  mv $tarball_name ../created-diego-release
popd
