#!/bin/sh

set -e

( cd diego-release-master && git rev-parse HEAD ) > generated-release/commitish

cf_dep_sha=$( cd cf-deployment && git rev-parse HEAD )

version=$(cat diego-final-releases/version)
echo "Diego v$version" > generated-release/name
echo "v$version" > generated-release/version
cat > generated-release/body <<EOF
## Resources

- [Download release v$version from bosh.io](https://bosh.io/releases/github.com/cloudfoundry/diego-release?version=$version).
- Verified with [cloudfoundry/cf-deployment @ \`$cf_dep_sha\`](https://github.com/cloudfoundry/cf-deployment/commit/$cf_dep_sha).
EOF
