#!/bin/bash

set -e

pushd ./deployments-diego/envs/${ENV_NAME}
  source .envrc
  credhub_path=$(credhub find -n "cf_admin_password" -j | jq -r .credentials[].name)
  cf_admin_password=$(credhub get  -n "${credhub_path}" -j | jq -r .value)
popd

cat > deployment-vars/vars.yml <<EOF
---
deployment: ${DEPLOYMENT_NAME}
system_domain: ${SYSTEM_DOMAIN}
cf_admin_password: ${cf_admin_password}"
EOF

cat deployment-vars/vars.yml
