#!/bin/bash

set -eu

VARS_FILE=$(ls deployment-vars/*.yml)
SYSTEM_DOMAIN=$(bosh int --path="/system_domain" $VARS_FILE)
CF_ADMIN_PASSWORD=$(bosh int --path="/cf_admin_password" $VARS_FILE)
DEPLOYMENT_NAME=$(bosh int --path="/deployment" $VARS_FILE)

cf api --skip-ssl-validation "https://api.$SYSTEM_DOMAIN"
cf auth admin $CF_ADMIN_PASSWORD

cleanup() {
  cf delete-org ${ORG} -f
  cf delete-quota ${RUNAWAY_QUOTA} -f
  rm -rf "$tmp_dir"
}

trap cleanup EXIT

# push a failing app for auctioneer metrics
cf create-org ${ORG}
cf target -o ${ORG}

cf create-space ${SPACE}
cf target -s ${SPACE}

cf create-quota ${RUNAWAY_QUOTA} -m ${RUNAWAY_MEMORY} -i -1 -r 10
cf set-quota ${ORG} ${RUNAWAY_QUOTA}

cf push ${APP_NAME} --docker-image cfdiegodocker/grace -m ${RUNAWAY_MEMORY} || true # expected to fail with insufficient resources

#for emitting app_instance_exceeded_log_rate_limit_count
tmp_dir=$(mktemp -d)
touch "$tmp_dir/file"
cf push yes -p "$tmp_dir" -b binary_buildpack -c yes -u none && sleep 10 && cf delete -f -r yes

OAUTH_TOKEN="$(cf oauth-token)"
INDICATOR_VERIFICATION=$(ls ./indicator-verification-linux/indicator-verification-linux*)
chmod +x $INDICATOR_VERIFICATION
find ./release/jobs -name "indicators.yml.erb" | xargs -n 1 -I{} $INDICATOR_VERIFICATION -indicators {} -metadata deployment=$DEPLOYMENT_NAME   -authorization "$OAUTH_TOKEN" -query-endpoint "https://$QUERY_ENDPOINT.$SYSTEM_DOMAIN" -k
