#!/bin/bash

set -eu

VARS_FILE=$(ls deployment-vars/*.yml)
SYSTEM_DOMAIN=$(bosh int --path="/system_domain" $VARS_FILE)
DEPLOYMENT_NAME=$(bosh int --path="/deployment" $VARS_FILE)

OAUTH_TOKEN="$(cf oauth-token)"
INDICATOR_VERIFICATION=$(ls ./indicator-verification-linux/indicator-verification-linux*)
chmod +x $INDICATOR_VERIFICATION
find ./release/jobs -name "indicators.yml.erb" | xargs -n 1 -I{} $INDICATOR_VERIFICATION -indicators {} -metadata deployment=$DEPLOYMENT_NAME   -authorization "$OAUTH_TOKEN" -query-endpoint "https://$QUERY_ENDPOINT.$SYSTEM_DOMAIN" -k
