#!/bin/bash

set -e -x -u

pushd diego-release
  echo "----- Set git identity"
  git config user.email "cf-diego+github@pivotal.io"
  git config user.name "CI (Automated)"

  echo "----- Adding master cloned release as remote"
  git remote add local-diego-release-master ../diego-release-master
  git fetch local-diego-release-master
  git merge --no-edit local-diego-release-master/master
popd

cp -a diego-release merged-master/
