#!/usr/bin/env bash

set -ex

export MERGED_CF_DEPLOYMENT=$PWD/merged-cf-deployment

pushd  ${PWD}/cf-deployment-diego
  sha=$(git rev-list --max-count=1 HEAD)
popd

pushd ${PWD}/cf-deployment
  echo "----- Set git identity"
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  echo "----- Adding cloned cf-deployment as remote"
  git remote add local-cf-deployment-diego ../cf-deployment-diego
  git fetch local-cf-deployment-diego

  echo "----- Merging cf-deployment branch diego"
  git merge --no-edit $sha

  cp -r . $MERGED_CF_DEPLOYMENT
popd
