#!/bin/bash

set -e -x

cat > $PWD/diego-release/config/private.yml <<EOF
---
blobstore:
  provider: s3
  options:
    secret_access_key: $secret_access_key
    access_key_id: $access_key_id
EOF

cd diego-release

bosh sync-blobs
old_envoy_version=$(ls -1 blobs/proxy/envoy*.tgz | xargs basename | sed 's/envoy-\(.*\).tgz/\1/g')
new_envoy_version=$(../envoy-binary/envoy --version | grep -vE '^$' | awk '{print $3}' | cut -d/ -f1)

if [[ "$old_envoy_version" == "$new_envoy_version" ]]; then
  echo "$new_envoy_version is currently the latest version."
  rsync -av $PWD/ ../updated-diego-release
  exit 0
fi


bosh remove-blob proxy/envoy-${old_envoy_version}.tgz
bosh add-blob ../envoy-binary/envoy.tgz proxy/envoy-${new_envoy_version}.tgz
sed -i "s/envoy.*\.tgz/envoy-${new_envoy_version}\.tgz/g" packages/proxy/*
bosh blobs
bosh upload-blobs
bosh blobs

pushd ../pr-message
  cat > description.md <<EOF
Bump envoy from [${old_envoy_version}]("https://github.com/envoyproxy/envoy/commit/${old_envoy_version}") to [${new_envoy_version}]("https://github.com/envoyproxy/envoy/commit/${new_envoy_version}")
EOF
  echo "Bump envoy to $(echo ${new_envoy_version} |  head -c 10)" > title.txt
popd

git --no-pager diff config/ packages/

git checkout -b bump-envoy

git config user.email "cf-diego+github@pivotal.io"
git config user.name "CI (Automated)"

git add -A config packages
git commit -n -F ../pr-message/title.txt
rsync -av $PWD/ ../updated-diego-release
