#!/bin/bash -exu

source cf-deployment-concourse-tasks/shared-functions

function update_runtime_configs() {
  local arguments=''
  for op in ${OPS_FILES}
  do
    arguments="${arguments} -o ops-files/${op}"
  done

  bosh --json config --column content --type runtime --name dns | jq .Tables[0].Rows[0].content -r > /tmp/original-runtime-config.yml
  bosh interpolate ${arguments} /tmp/original-runtime-config.yml > /tmp/runtime-config.yml
  bosh -n update-runtime-config --name dns /tmp/runtime-config.yml
}

function main() {
  setup_bosh_env_vars
  update_runtime_configs
}

main
