#!/bin/bash

set -e -x

cat > $PWD/diego-release/config/private.yml <<EOF
---
blobstore:
  provider: s3
  options:
    secret_access_key: $secret_access_key
    access_key_id: $access_key_id
EOF

cd diego-release

bosh sync-blobs
old_envoy_version=$(ls -1 blobs/proxy/envoy*.tgz | xargs basename | sed 's/envoy-\(.*\).tgz/\1/g')
new_envoy_version=$(../envoy-binary/envoy --version | grep -vE '^$' | awk '{print $3}' | cut -d/ -f1)

bosh remove-blob proxy/envoy-${old_envoy_version}.tgz
bosh add-blob ../envoy-binary/envoy.tgz proxy/envoy-${new_envoy_version}.tgz
sed -i "s/envoy.*\.tgz/envoy-${new_envoy_version}\.tgz/g" packages/proxy/*
bosh blobs
bosh upload-blobs
bosh blobs
git --no-pager diff config/ packages/

git config user.email "cf-diego+github@pivotal.io"
git config user.name "CI (Automated)"

git add -A config packages
msg_file=$(mktemp)
cat > ${msg_file} <<EOF
Bumping envoy from ${old_envoy_version} to ${new_envoy_version}

$(cat ../issue-file/link)
EOF
git commit -n -F ${msg_file}
rsync -av $PWD/ ../updated-diego-release
