#!/bin/bash

set -e -x

cat > $PWD/diego-release/config/private.yml <<EOF
---
blobstore:
  provider: s3
  options:
    secret_access_key: $secret_access_key
    access_key_id: $access_key_id
EOF

pushd golang-release
	new_go_version=$(bosh blobs | grep linux | grep go1. | cut -d . -f 1-3 | sort | tail -1)
popd

cd diego-release

bosh vendor-package golang-1-linux ../golang-release
bosh vendor-package golang-1-windows ../golang-release

git --no-pager diff packages .final_builds

git config user.email "cf-diego@pivotal.io"
git config user.name "CI (Automated)"

git checkout -b bump-golang
git add -A packages .final_builds
git commit -n -m "Bump Golang to $new_go_version"
rsync -av $PWD/ ../updated-diego-release
