#!/bin/bash

set -e -x
DATE=$(date '+%Y-%m-%d %H:%M:%S')

cat > $PWD/diego-release/config/private.yml <<EOF
---
blobstore:
  provider: s3
  options:
    secret_access_key: $secret_access_key
    access_key_id: $access_key_id
EOF

pushd golang-release
	new_go_version=$(bosh blobs | grep linux | grep go1. | cut -d . -f 1-3 | sort | tail -1)
popd

pushd pr-message
  cat > description.md <<EOF

Bump Dockerfile golang version
- [ ] [Example bump for previous go version](https://github.com/cloudfoundry/diego-ci/blob/master/pipelines/docker-pipeline.yml#L15)
- [ ] Sync pipelines

Acceptance
- [ ] Check the progress of the bump in [diego-ci](https://ci.funtime.lol/teams/diego/pipelines/main). Confirm all jobs have passed and [release-candidate branch](https://github.com/cloudfoundry/diego-release/tree/release-candidate) has been bumped

EOF

echo "Bump Golang to $new_go_version" > title.txt

popd

cd diego-release
echo "This file was updated by CI on ${DATE}" > docs/go.version
echo "$new_go_version" >> docs/go.version

bosh vendor-package golang-1-linux ../golang-release
bosh vendor-package golang-1-windows ../golang-release

git --no-pager diff packages .final_builds

git config user.email "cf-diego+github@pivotal.io"
git config user.name "CI (Automated)"

git checkout -b bump-golang
git add -A packages .final_builds
git add docs/go.version
git commit -n -F "../pr-message/title.txt"
rsync -av $PWD/ ../updated-diego-release
