FROM mcr.microsoft.com/windows/nanoserver:1809

LABEL org.cloudfoundry.groot-windows-test-regularfile.dockerfile.url="https://github.com/cloudfoundry/wg-app-platform-runtime-ci/blob/main/winc-release/dockerfiles/regularfile/Dockerfile"
LABEL org.cloudfoundry.groot-windows-test-regularfile.notes.md="Used by winc-release \
"

RUN mkdir C:\temp\test & echo hello > C:\temp\test\hello
