#@ load("@ytt:data", "data")
#@ load("ytt-helpers.star", "helpers")

#! Define-Groups
groups:
- name: release
  jobs:
  - manual-release-trigger
  - bump-windowsfs-online-release
  - claim-env
  - prepare-env
  - run-wats
  - export-release
  - ship-what
  - ship-it

- name: periodics
  jobs:
  - bump-dependencies-go-mod
  - bump-package-golang

- name: cleanup
  jobs:
  - cleanup-time-gate
  - wait-for-env-lock-claim
  - wait-for-acceptance-tests
  - manual-cleanup-trigger
  - cleanup-env
  - force-cleanup-env
  - release-env-lock

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: us-central1-docker.pkg.dev/app-runtime-platform-wg/dockerhub-mirror/cfcommunity/slack-notification-resource
    username: _json_key
    password: ((gcp-arp-artifact-registry-service-account-token))
    tag: latest

- name: fork-pool
  type: registry-image
  source:
    repository: ebroberson/pool-resource

#! Define-Resources
resources:
- name: windows2016fs
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/windows2016fs.git
    paths: [ 2019/IMAGE_TAG ]

- name: repo
  type: git
  icon: source-branch
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/windowsfs-online-release.git
    private_key: ((github-appruntimeplatform-bot/private-key))
    ignore_paths:
    - .github/
    - .gitignore
    - CODEOWNERS
    - LICENSE
    - NOTICE
    - README.md
    - docs/

- name: release-branch 
  type: git
  icon: source-branch
  source:
    uri: git@github.com:cloudfoundry/windowsfs-online-release.git
    branch: release
    private_key: ((github-appruntimeplatform-bot/private-key))

- name: develop-branch-mergeback
  type: git
  icon: source-branch
  source:
    uri: git@github.com:cloudfoundry/windowsfs-online-release.git
    branch: develop
    private_key: ((github-appruntimeplatform-bot/private-key))
    
- name: ci
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci

- name: windowsfs-online-release-env-lock
  type: fork-pool
  icon: cloud-lock
  source:
    branch: main
    pool: windowsfs-online-release-env-lock 
    private_key: ((github-appruntimeplatform-bot/private-key))
    uri: git@github.com:cloudfoundry/runtime-ci-pools.git
    paths: windowsfs-online-release-env-lock 

- name: cf-deployment
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: cf-deployment-concourse-tasks
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: cf-acceptance-tests
  type: git
  icon: source-branch
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-acceptance-tests


- name: image
  type: registry-image
  icon: docker
  source:                                        
    repository: us-central1-docker.pkg.dev/app-runtime-platform-wg/dockerhub-mirror/cloudfoundry/tas-runtime-build
    username: _json_key
    password: ((gcp-arp-artifact-registry-service-account-token))
    tag: 'latest'

- name: slack-ci-channel
  type: slack-notification
  source:
    url: ((slack-ci-channel/webhook))

- name: env
  type: git
  icon: sheep
  source:
    branch: main
    uri: git@github.com:cloudfoundry/app-runtime-platform-envs
    private_key: ((github-appruntimeplatform-bot/private-key))
    paths:
      - bbl-windowsfs-online-env

- name: github-release
  type: github-release
  icon: github
  source:
    access_token: ((github-appruntimeplatform-bot/access-token))
    repository: windowsfs-online-release
    owner: cloudfoundry

- name: draft-github-release 
  type: github-release
  icon: github
  source:
    access_token: ((github-appruntimeplatform-bot/access-token))
    drafts: true
    repository: windowsfs-online-release
    owner: cloudfoundry

- name: version
  type: semver
  icon: counter
  source:
    driver: gcs
    bucket: ci-release-versions
    key: windowsfs-online-release//version
    json_key: ((gcp-wg-arp-oss-service-account/config-json))
    initial_version: 2.62.0

- name: go-version
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci
    paths: [go-version.json]

- name: golang-release-latest
  type: git
  icon: tag-outline
  source:
    tag_filter: v*
    uri: https://github.com/bosh-packages/golang-release.git

- name: weekly
  type: time
  icon: clock
  source:
    interval: '168h'
    start: 04:00
    stop: 04:59
    days:
      - Wednesday

- name: env-weekly
  type: time
  icon: clock
  source:
    interval: '168h'
    start: 01:00
    stop: 01:59
    days:
      - Thursday

- name: cleanup-timer
  type: time
  icon: clock
  source:
    interval: '1h'

- name: manual-release-trigger
  type: time
  source:
    interval: '1m'

- name: manual-cleanup-trigger
  type: time
  source:
    interval: '1m'

#! Define-Jobs
jobs:
- name: manual-release-trigger
  plan:
  - put: manual-release-trigger

- name: manual-cleanup-trigger
  plan:
  - put: manual-cleanup-trigger

- name: bump-dependencies-go-mod
  serial: true
  on_failure: &ci-notification
    put: slack-ci-channel
    params:
      text: ":concourse-failed: $BUILD_PIPELINE_NAME failed on <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_JOB_NAME>."
  plan:
  - in_parallel:
      steps:
      - get: ci
      - get: repo
      - get: image
      - get: weekly
        trigger: true
  - task: windowsfs-online-bump-dependencies-go-mod
    image: image
    file: ci/shared/tasks/bump-dependencies-go-mod/linux.yml
  - put: repo
    params:
      rebase: true
      repository: bumped-repo

- name: bump-package-golang
  on_failure: *ci-notification
  plan:
  - in_parallel:
    - get: ci
    - get: repo
    - get: image
    - get: go-version
      trigger: true
    - get: golang-release-latest
      trigger: true

  - task: bump-golang-package-name
    image: image
    file: ci/shared/tasks/bump-golang-package-name/linux.yml
    params:
      PLATFORM: windows

  - task: bump-golang-linux
    file: ci/shared/tasks/bosh-vendor-package/linux.yml
    image: image
    input_mapping:
      repo: bumped-repo
      package-release: golang-release-latest
    params:
      PACKAGE_NAME: golang-*-windows
      AWS_ACCESS_KEY_ID: ((aws-s3-svc-gdn-win-bosh-s3/access-key-id))
      AWS_SECRET_ACCESS_KEY: ((aws-s3-svc-gdn-win-bosh-s3/secret-access-key))
      AWS_ASSUME_ROLE_ARN: ((aws-s3-svc-gdn-win-bosh-s3/assume-role))

  - put: repo
    params:
      rebase: true
      repository: vendored-repo
- name: bump-windowsfs-online-release
  serial: true
  on_failure: *ci-notification
  plan:
  - in_parallel:
    - get: ci
    - get: repo
    - get: windows2016fs
      trigger: true
    - get: image
  - task: combine-assets
    file: ci/shared/tasks/combine-assets/linux.yml
    image: image
    input_mapping:
      input-01: windows2016fs
    output_mapping:
      combined-assets: version
    params:
      COPY_ACTIONS: |
        {input-01/2019/IMAGE_TAG,combined-assets/version}
  - task: bump-repo-windows2016fs-version
    file: ci/shared/tasks/bump-repo-version-file/linux.yml
    image: image
    params:
      BUMP_ACTION: |
        cat packages/windows2019fs/packaging \
          | sed /^\$image_tag/d \
          | sed "/^\$image_name/ a \$image_tag=\"${VERSION}\"" \
          > packaging.tmp
        mv packaging.tmp packages/windows2019fs/packaging
  - put: repo
    params:
      rebase: true
      repository: bumped-repo


- name: claim-env
  serial: true
  on_abort: &release-env-lock
    do:
      - put: windowsfs-online-release-env-lock
        params:
          release: windowsfs-online-release-env-lock
  on_failure: *release-env-lock
  plan:
  - in_parallel:
    - get: manual-release-trigger
      trigger: true
      passed: [ manual-release-trigger ] 
    - get: ci 
    - get: repo 
      passed: [ bump-windowsfs-online-release ]
    - get: env-weekly
      trigger: true
    - get: image
    - get: env
    - get: windows2016fs
      passed: [ bump-windowsfs-online-release ]
    - get: windowsfs-online-release-env-lock
  - put: windowsfs-online-release-env-lock
    params:
      claim: windowsfs-online-release-env-lock
  - task: start-bbl-envs
    image: image
    file: ci/shared/tasks/start-gcp-instance/linux.yml
    input_mapping:
      bbl-state: env
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-ci-bbl-service-account/config-json))
      BBL_STATE_DIR: bbl-windowsfs-online-env
      RESUME: false
  - task: wait-for-bosh-api
    file: ci/shared/tasks/wait-for-bosh-api/linux.yml
    image: image
    params:
      BBL_STATE_DIR: bbl-windowsfs-online-env

- name: prepare-env
  serial: true
  on_abort: *release-env-lock
  on_failure: *release-env-lock
  plan:
  - in_parallel:
    - get: manual-release-trigger
      trigger: true
      passed: [ claim-env ] 
    - get: ci
    - get: repo
      trigger: true
      passed: [claim-env]
    - get: image
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: env
      passed: [claim-env]
      trigger: true
    - get: windows2016fs
      passed: [claim-env]
    - get: windowsfs-online-release-env-lock
      passed: [claim-env]
  - try: &delete-cf-deployment
      do:
        - task: bosh-deld
          image: image
          file: ci/shared/tasks/bosh-deld/linux.yml
          params:
            BBL_STATE_DIR: bbl-windowsfs-online-env
            DEPLOYMENT_NAME: cf
  - task: combine-ops-files
    file: ci/shared/tasks/combine-assets/linux.yml
    image: image
    input_mapping:
      input-01: cf-deployment
    params:
      COPY_ACTIONS: |
        {input-01/operations/use-compiled-releases.yml,combined-assets}
        {input-01/operations/experimental/use-compiled-releases-windows.yml,combined-assets}
        {input-01/operations/windows2019-cell.yml,combined-assets}
        {input-01/operations/use-online-windows2019fs.yml,combined-assets}
  - task: deploy-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      ops-files: combined-assets
      release: repo
      bbl-state: env
    params:
      BBL_STATE_DIR: bbl-windowsfs-online-env
      SYSTEM_DOMAIN: bbl-windowsfs-online-env.arp.cloudfoundry.org
      DEPLOY_WITH_UPTIME_MEASUREMENTS: "false"
      FAIL_ON_DOWNTIME: "false"
      OPS_FILES: #@ "\n".join(data.values.opsfiles)
  - task: open-asg-for-credhub
    file: cf-deployment-concourse-tasks/open-asgs-for-bosh-instance-group/task.yml
    input_mapping:
      bbl-state: env
    params:
      BBL_STATE_DIR: bbl-windowsfs-online-env
      SYSTEM_DOMAIN: bbl-windowsfs-online-env.arp.cloudfoundry.org
      INSTANCE_GROUP_NAME: credhub
      SECURITY_GROUP_NAME: credhub
  - task: open-asg-for-uaa
    file: cf-deployment-concourse-tasks/open-asgs-for-bosh-instance-group/task.yml
    input_mapping:
      bbl-state: env
    params:
      BBL_STATE_DIR: bbl-windowsfs-online-env
      SYSTEM_DOMAIN: bbl-windowsfs-online-env.arp.cloudfoundry.org
      INSTANCE_GROUP_NAME: uaa
      SECURITY_GROUP_NAME: uaa
  - task: enable-feature-flags-for-cats
    file: cf-deployment-concourse-tasks/set-feature-flags/task.yml
    input_mapping:
      bbl-state: env
    params:
      BBL_STATE_DIR: bbl-windowsfs-online-env
      SYSTEM_DOMAIN: bbl-windowsfs-online-env.arp.cloudfoundry.org
      ENABLED_FEATURE_FLAGS: diego_docker service_instance_sharing

- name: run-wats
  serial: true
  serial_groups: [acceptance]
  plan:
  - in_parallel:
    - get: manual-release-trigger
      trigger: true
      passed: [ prepare-env ] 
    - get: ci
    - get: repo
      passed: [prepare-env]
      trigger: true
    - get: image
    - get: env
      passed: [prepare-env]
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: cf-acceptance-tests
    - get: cf-deployment
    - get: windows2016fs
      passed: [prepare-env]
  - task: create-cats-config
    image: image
    file: ci/shared/tasks/build-acceptance-test-configs/linux.yml
    params:
      CONFIGS: wats
      WITH_ISOSEG: true
      WITH_DYNAMIC_ASG: true
      BBL_STATE_DIR: bbl-windowsfs-online-env
  - task: wats
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    attempts: 2
    input_mapping:
      integration-config: built-acceptance-test-configs
    params:
      CONFIG_FILE_PATH: wats.json
      NODES: "4"
      SKIP_REGEXP: Syslog drain

- name: export-release
  serial: true
  serial_groups: [acceptance]
  plan:
  - in_parallel:
    - get: manual-release-trigger
      trigger: true
      passed: [ prepare-env ] 
    - get: ci
    - get: repo
      passed: [prepare-env]
      trigger: true
    - get: image
    - get: env
      passed: [prepare-env]
      trigger: true
    - get: windows2016fs
      passed: [prepare-env]
    - get: cf-deployment-concourse-tasks
  - task: export-release
    file: ci/shared/tasks/bosh-export-release/linux.yml
    image: image
    params:
      OS: windows
      BBL_STATE_DIR: bbl-windowsfs-online-env

- name: ship-what
  on_success:
    put: slack-ci-channel
    params:
      text: ":concourse-succeeded: $BUILD_PIPELINE_NAME ship-what just ran. Maybe you should cut a release? $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME"
  plan:
    - in_parallel:
        steps:
        - get: manual-release-trigger
          trigger: true
          passed:
            - run-wats
            - export-release
        - get: ci
        - get: repo
          passed:
            - run-wats
            - export-release
          trigger: true
        - get: image
        - get: release-branch
          params:
            submodules: none
        - get: github-release
        - get: version
        - get: env
          passed:
            - run-wats
            - export-release
          trigger: true
        - get: windows2016fs
          passed:
            - run-wats
            - export-release

    - task: check-safe-to-release-repo
      image: image
      file: ci/shared/tasks/check-safe-to-release-repo/linux.yml
      input_mapping:
        release-repo: release-branch

    - task: extract-metadata
      file: ci/shared/tasks/combine-assets/linux.yml
      image: image
      input_mapping:
        input-01: windows2016fs
      output_mapping:
        combined-assets: extra-metadata
      params:
        COPY_ACTIONS: |
          {input-01/2019/kb-metadata,combined-assets}

    - task: build-release-notes-windowsfs-online-release
      image: image
      file: ci/shared/tasks/build-release-notes/linux.yml
      input_mapping:
        previous-github-release: github-release

- name: ship-it
  serial: true
  plan:
    - in_parallel:
        steps:
        - get: ci
        - get: repo
          passed: [ ship-what ]
        - get: image
        - get: release-branch
          params:
            submodules: none
        - get: github-release
        - get: version
        - get: develop-branch-mergeback
          params:
            submodules: none
        - get: windows2016fs
          passed: [ ship-what ]

    - task: check-safe-to-release-branch
      image: image
      file: ci/shared/tasks/check-safe-to-release-repo/linux.yml
      input_mapping:
        release-repo: release-branch

    - task: extract-metadata
      file: ci/shared/tasks/combine-assets/linux.yml
      image: image
      input_mapping:
        input-01: windows2016fs
      output_mapping:
        combined-assets: extra-metadata
      params:
        COPY_ACTIONS: |
          {input-01/2019/kb-metadata,combined-assets}

    - task: build-release-notes-windowsfs-online-release
      image: image
      file: ci/shared/tasks/build-release-notes/linux.yml
      input_mapping:
        previous-github-release: github-release

    - task: bosh-finalize-release
      image: image
      file: ci/shared/tasks/bosh-finalize-release/linux.yml
      params:
        AWS_ACCESS_KEY_ID: ((aws-s3-svc-gdn-win-bosh-s3/access-key-id))
        AWS_SECRET_ACCESS_KEY: ((aws-s3-svc-gdn-win-bosh-s3/secret-access-key))
        AWS_ASSUME_ROLE_ARN: ((aws-s3-svc-gdn-win-bosh-s3/assume-role))

    - put: release-branch
      params:
        repository: finalized-release-repo
        tag: version/number
        tag_prefix: v

    - task: merge-release-onto-develop
      image: image
      file: ci/shared/tasks/git-merge-branches/linux.yml
      input_mapping:
        source-branch: release-branch
        onto-branch: develop-branch-mergeback
      params:
        SOURCE_BRANCH_NAME: release
        ONTO_BRANCH_NAME: develop

    - in_parallel:
        steps:
        - put: draft-github-release
          params:
            name: version/number
            tag: version/number
            tag_prefix: v
            body: built-release-notes/notes.md
            globs:
            - finalized-release-tarball/windowsfs-*.tgz
        - put: develop-branch-mergeback
          params:
            repository: merged-branch
            merge: true

    - get: next-version
      resource: version
      params: {bump: minor}
    - put: next-version
      resource: version
      params: {file: next-version/number}

- name: cleanup-time-gate
  plan:
  - get: cleanup-timer
    trigger: true

- name: wait-for-env-lock-claim
  serial: true
  plan:
  - get: cleanup-timer
    trigger: true
    passed: [ cleanup-time-gate ]
  - get: windowsfs-online-release-env-lock
  - put: check-unclaimed-env-lock
    resource: windowsfs-online-release-env-lock
    params:
      check_unclaimed: windowsfs-online-release-env-lock
      retry-delay: 15m

- name: wait-for-acceptance-tests
  plan:
  - get: image
  - get: windowsfs-online-release-env-lock
    passed: [ wait-for-env-lock-claim ]
    trigger: true
  - task: sleep
    image: image
    config:
      platform: linux
      run: 
        path: sh
        args:
        - -exc
        - sleep 4h

- name: cleanup-env
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: ci
      - get: env
      - get: image
      - get: manual-cleanup-trigger
        trigger: true
        passed: [ manual-cleanup-trigger ]
      - get: windowsfs-online-release-env-lock
        passed: [ wait-for-acceptance-tests ]
        trigger: true
  - try: *delete-cf-deployment
  - task: stop-bbl-envs
    image: image
    file: ci/shared/tasks/stop-gcp-instance/linux.yml
    input_mapping:
      bbl-state: env
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-ci-bbl-service-account/config-json))
      BBL_STATE_DIR: bbl-windowsfs-online-env
      SUSPEND: false
  - try: *release-env-lock

- name: release-env-lock
  plan:
  - get: windowsfs-online-release-env-lock
  - try: *release-env-lock

- name: force-cleanup-env
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: ci
      - get: env
      - get: image
  - try: *delete-cf-deployment
  - task: stop-bbl-envs
    image: image
    file: ci/shared/tasks/stop-gcp-instance/linux.yml
    input_mapping:
      bbl-state: env
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-ci-bbl-service-account/config-json))
      BBL_STATE_DIR: bbl-windowsfs-online-env
      SUSPEND: false
