---
platform: linux

inputs:
- name: ci
- name: repo
- name: ci-config
  optional: true

params:
  DEFAULT_PARAMS:
  LINTERS: |
    sync-package-specs.bash
    sync-submodule-config.bash
    match-golang-os-package-versions.bash

run:
  path: ci/shared/tasks/lint-repo/task.bash
