name: ((DEPLOYMENT_NAME))

releases:
- name: garden-runc
  version: latest
- name: bpm
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release
  version: latest

stemcells:
- alias: stemcell
  os: ((CF_STEMCELL_OS))
  version: latest

instance_groups:
- name: gats
  instances: 1
  vm_type: ((CF_VM_TYPE))
  networks:
  - name: ((CF_NETWORK))
  azs: [((CF_AZ))]
  stemcell: stemcell
  jobs:
  - name: bpm
    release: bpm
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        debug_listen_address: 0.0.0.0:17013
        log_level: debug
        dns_servers: [169.254.0.2, 169.254.0.53]
        experimental_cpu_throttling: ((WITH_CPU_THROTTLING))
        bpm:
          enabled: ((WITH_BPM))
        destroy_containers_on_start: ((WITH_BPM))
        containerd_mode: ((WITH_CONTAINERD_MODE))
  - name: gats
    release: garden-runc
    properties:
      cpu_throttling: ((WITH_CPU_THROTTLING))
      garden_test_rootfs: "docker:///cloudfoundry/garden-rootfs"
- name: gpats
  instances: 1
  vm_type: ((CF_VM_TYPE))
  networks:
  - name: ((CF_NETWORK))
  azs: [((CF_AZ))]
  stemcell: stemcell
  jobs:
  - name: bpm
    release: bpm
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        dns_servers: [169.254.0.2, 169.254.0.53]
        debug_listen_address: 0.0.0.0:17013
        log_level: debug
  - name: gpats
    release: garden-runc

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
