---
readme: |
  This task will determine image tag for the golang version specified in GO_VERSION_FILE for a repo or an image. 
oses:
  - linux
extra_inputs:
  repo: The presence of this input will determine if the task need to generate tags for an image or a repo.
params:
  GO_VERSION_FILE: (Defaults to ci/go-version.json). Path to go-version.json where the new version is defined.
  IMAGE: (Defaults to cloudfoundry/tas-runtime-build) The image name in dockerhub.
