---
platform: linux

inputs:
- name: ci
- name: repo
- name: env

outputs:
- name: prepared-env

params:
  BBL_STATE_DIR:
  FUNCTIONS:
  VARS:
run:
  path: ci/shared/tasks/run-bin-prepare-cf-deployment-env/task.bash
