---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/garden-windows-ci

inputs:
- name: ci
- name: cf-deployment

outputs:
- name: stemcell

run:
  path: ci/garden-windows/tasks/get-gcp-linux-stemcell/run

params:
  bosh_manifest_path: cf-deployment/cf-deployment.yml
