#!/usr/bin/env bash

set -eu

. ci/garden-windows/bin/ci_helpers

trap _close_ssh_connection EXIT
cmd=$(_bosh_socks5_env "$JUMPBOX_IP" "$JUMPBOX_SSH_KEY")
eval "$cmd"

bosh -n -d "${BOSH_DEPLOYMENT}" deld --force

bosh -n clean-up

bosh disks --orphaned --json | jq -r .Tables[0].Rows[].disk_cid | xargs -I {} bosh -n delete-disk {}
