---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/garden-windows-ci

inputs:
- name: ci

run:
  path: ci/garden-windows/tasks/bosh-deld/run

params:
  BOSH_DEPLOYMENT: cf
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  JUMPBOX_IP:
  JUMPBOX_SSH_KEY:
