---
platform: windows

inputs:
  - name: ci
  - name: winc-release

outputs:
  - name: generated-readme

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/garden-windows/tasks/winc-release-readme/run.ps1

params:
  WINC_TEST_ROOTFS:
