---
readme: |
  This task will delete and clean-up deployment.
oses:
  - linux
params:
  BBL_STATE_DIR: name of bbl state dir (relative to the env resource)
  DEPLOYMENT_NAME: Name of deployment (required unless ALL_DEPLOYMENTS is true)
  ALL_DEPLOYMENTS: (Defaults to false) When true, deletes all deployments found on the director; DEPLOYMENT_NAME is ignored
  DIR: (Defaults to .) Change DIR before running bosh_target
