---
platform: windows

inputs:
- name: ci
- name: version
- name: repo
- name: git-setup
- name: vcredist-2010
- name: vcredist-2010-x86
- name: vcredist-ucrt
- name: vcredist-ucrt-x86
- name: upstream-image
- name: dotnet-48-installer
  optional: true

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/garden-windows/tasks/docker-build-and-push/run.ps1

params:
  DOCKERFILE: ""
  IMAGE_NAME: ""
  DOCKER_USERNAME: ""
  DOCKER_PASSWORD: ""
  OS_VERSION: ""
  SHARE_IP:
  SHARE_FQDN:
  SHARE_NAME:
  SHARE_USERNAME:
  SHARE_PASSWORD:
