---
platform: windows

inputs:
- name: ci
- name: web-config-buildpack

run:
  path: powershell
  args:
    - "-ExecutionPolicy"
    - "Bypass"
    - "-File"
    - ci/garden-windows/tasks/test-web-config-buildpack-windows/run.ps1
