#@ load("@ytt:data", "data")
#@ load("ytt-helpers.star", "helpers")

groups:
- name: individual
  jobs:
  - state-claim-env
  - state-reset
  - state-unclaim-env
  - state-update-acceptance-test
  - state-update-job
  - state-lock
  - state-unlock

- name: cleanup-flow
  jobs:
  - check-pipeline-state
  - cleanup

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: ci
  type: git
  icon: source-branch
  source:
    branch: ci-pipeline-state
    uri: git@github.com:cloudfoundry/wg-app-platform-runtime-ci
    private_key: ((github-appruntimeplatform-bot/private-key))

- name: image
  type: registry-image
  icon: docker
  source:                                        
    repository: us-central1-docker.pkg.dev/app-runtime-platform-wg/dockerhub-mirror/cloudfoundry/tas-runtime-build
    username: _json_key
    password: ((gcp-arp-artifact-registry-service-account-token))
    tag: latest

jobs:
- name: state-reset
  plan:
  - in_parallel:
    - get: ci
    - get: image
  - task: reset-pipeline-state
    image: image
    file: ci/shared/tasks/manage-pipeline-state/linux.yml
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-oss-service-account/config-json))
      BUCKET: #@ data.values.pipeline_state.bucket
      STATE_PATH: #@ data.values.pipeline_state.state_path
      COMMAND: reset
      ACCEPTANCE_JOBS: #@ "\n".join(data.values.pipeline_state.acceptance_jobs)

- name: state-lock
  plan:
  - in_parallel:
    - get: ci
    - get: image
  - task: lock-state
    image: image
    file: ci/shared/tasks/manage-pipeline-state/linux.yml
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-oss-service-account/config-json))
      BUCKET: #@ data.values.pipeline_state.bucket
      STATE_PATH: #@ data.values.pipeline_state.state_path
      COMMAND: lock

- name: state-unlock
  plan:
  - in_parallel:
    - get: ci
    - get: image
  - task: unlock-state
    image: image
    file: ci/shared/tasks/manage-pipeline-state/linux.yml
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-oss-service-account/config-json))
      BUCKET: #@ data.values.pipeline_state.bucket
      STATE_PATH: #@ data.values.pipeline_state.state_path
      COMMAND: unlock

- name: state-claim-env
  plan:
  - in_parallel:
    - get: ci
    - get: image
  - task: claim-env
    image: image
    file: ci/shared/tasks/manage-pipeline-state/linux.yml
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-oss-service-account/config-json))
      BUCKET: #@ data.values.pipeline_state.bucket
      STATE_PATH: #@ data.values.pipeline_state.state_path
      COMMAND: claim

- name: state-unclaim-env
  plan:
  - in_parallel:
    - get: ci
    - get: image
  - task: unclaim-env
    image: image
    file: ci/shared/tasks/manage-pipeline-state/linux.yml
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-oss-service-account/config-json))
      BUCKET: #@ data.values.pipeline_state.bucket
      STATE_PATH: #@ data.values.pipeline_state.state_path
      COMMAND: unclaim

- name: state-update-job
  plan:
  - in_parallel:
    - get: ci
    - get: image
  - task: update-job-claim-env
    image: image
    file: ci/shared/tasks/manage-pipeline-state/linux.yml
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-oss-service-account/config-json))
      BUCKET: #@ data.values.pipeline_state.bucket
      STATE_PATH: #@ data.values.pipeline_state.state_path
      COMMAND: update-job
      JOB: claim-env
      STATE: pass

- name: state-update-acceptance-test
  plan:
  - in_parallel:
    - get: ci
    - get: image
  - task: update-acceptance-cats
    image: image
    file: ci/shared/tasks/manage-pipeline-state/linux.yml
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-oss-service-account/config-json))
      BUCKET: #@ data.values.pipeline_state.bucket
      STATE_PATH: #@ data.values.pipeline_state.state_path
      COMMAND: acceptance
      TEST: run-cats
      STATE: fail

