resource_types:
- name: cogito
  type: registry-image
  check_every: 168h
  source:
    repository: pix4d/cogito

groups:
- name: main
  jobs:
  - lint-ci

resources:
- name: ci
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci
- name: tas-runtime-build
  type: docker-image
  icon: docker
  source:
    repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/cloudfoundry/tas-runtime-build
    username: _json_key
    password: ((gcp-tas-runtime-service-account/config-json))
    tag: 'latest'
- name: chat-notify
  type: cogito
  check_every: never
  source:
    sinks:
      - gchat
    gchat_webhook: ((concourse-google-chat-webhook))

meta:
  gchat_notification: &gchat_notification
    on_failure:
      put: chat-notify
      params:
        state: failure
    on_error:
      put: chat-notify
      params:
        state: error

jobs:
- name: lint-ci
  serial: true
  <<: *gchat_notification
  plan:
  - in_parallel:
      steps:
      - get: ci
        trigger: true
      - get: tas-runtime-build
  - task: test-ci-configurations
    image: tas-runtime-build
    file: ci/shared/tasks/lint-ci/linux.yml
