groups:
- name: main
  jobs:
  - lint-ci
resources:
- name: ci
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci
- name: tas-runtime-build
  type: registry-image
  icon: docker
  source:
    repository: us-central1-docker.pkg.dev/app-runtime-platform-wg/dockerhub-mirror/cloudfoundry/tas-runtime-build
    username: _json_key
    password: ((gcp-arp-artifact-registry-service-account-token))
    tag: 'latest'

jobs:
- name: lint-ci
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: ci
        trigger: true
      - get: tas-runtime-build
  - task: test-ci-configurations
    image: tas-runtime-build
    file: ci/shared/tasks/lint-ci/linux.yml
