groups:
- name: main
  jobs:
  - go-clean-cache-windows

resources:
- name: ci
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci
- name: image
  type: docker-image                             
  icon: docker
  source:                                        
    repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/cloudfoundry/tas-runtime-build
    username: _json_key
    password: ((gcp-tas-runtime-service-account/config-json))
    tag: 'latest'
- name: late-at-night
  type: time
  icon: clock
  source:
    start: 11:00 PM
    stop: 11:30 PM
    location: America/New_York

jobs:
- name: go-clean-cache-windows
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: late-at-night
        trigger: true
      - get: ci
      - get: image
  - in_parallel:
    - do:
    - task: go-clean-cache-on-windows-worker
      file: ci/shared/tasks/go-clean-cache/windows.yml
    - task: go-clean-cache-on-diego-windows-worker
      tags: [ diego-windows ]
      file: ci/shared/tasks/go-clean-cache/windows.yml
