readme: |
  This task waits for the BOSH API to come alive on a toolsmiths/shepherd environment. We use this when claiming
  envs to avoid hours of deployment/compilation waste when shepherd environments have broken DNS.
oses:
  - linux
inputs:
   - env
params:
  BBL_STATE_DIR: path to the bbl state directory (relative to the env input)
