#!/bin/bash

# There is a cf-deployment-concourse-task that achieves something similiar
# to this script but opens up all the ports and needs to be executed for each security group.
# github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/master/open-asgs-for-bosh-instance-group/task.yml

set -e

. ci/garden-windows/bin/ci_helpers

trap _close_ssh_connection EXIT
cmd=$(_bosh_socks5_env "$JUMPBOX_IP" "$JUMPBOX_SSH_KEY")
eval "$cmd"

asgJson=$(mktemp)


credhubIPs=$(bosh -d $DEPLOYMENT_NAME instances | grep credhub | awk '{print $4}')
echo "$credhubIPs" | jq -R '{"protocol": "tcp", "destination": ., "ports": "8844"}' | jq -s . > "$asgJson"

cf api "$CF_API" --skip-ssl-validation
cf login -u "$CF_USERNAME" -p "$CF_PASSWORD"  -o "system" --skip-ssl-validation

cf set-running-environment-variable-group '{"CREDHUB_API": "https://credhub.service.cf.internal:8844"}'

cf delete-security-group -f credhub-internal
cf create-security-group credhub-internal "$asgJson"

cf bind-running-security-group credhub-internal
cf bind-staging-security-group  credhub-internal


uaaIPs=$(bosh -d $DEPLOYMENT_NAME instances | grep uaa | awk '{print $4}')
echo "$uaaIPs" | jq -R '{"protocol": "tcp", "destination": ., "ports": "8443"}' | jq -s . > "$asgJson"
cf delete-security-group -f uaa-internal
cf create-security-group uaa-internal "$asgJson"

cf bind-running-security-group uaa-internal
