---
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/garden-windows-ci

platform: linux

inputs:
- name: ci

params:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  JUMPBOX_IP:
  JUMPBOX_SSH_KEY:
  DEPLOYMENT_NAME: cf
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:

run:
  path: ci/garden-windows/tasks/enable-credhub/run
