---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: ci-config
    optional: true

outputs:
  - name: synced-repo 

run:
  path: ci/shared/tasks/sync-dot-github-dir/task.bash

params:
  PARENT_TEMPLATE_DIR:
