---
platform: linux

inputs:
- name: ci
- name: env
- name: release-01
  optional: true
- name: release-02
  optional: true
- name: release-03
  optional: true

params:
  BBL_STATE_DIR:

run:
  path: ci/shared/tasks/bosh-upload-dev-releases/task.bash
