---
platform: windows

inputs:
  - name: ci
  - name: web-config-buildpack

outputs:
  - name: artifacts

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/garden-windows/tasks/web-config-github-shipit/run.ps1

params:
  BRANCH:
  GITHUB_AUTH_TOKEN:
