#!/usr/bin/env bash

set -eu

blob_version=$(grep $FS_VERSION windowsfs-release/config/blobs.yml |  grep -o '[0-9]\+.[0-9]\+.[0-9]\+')
image_version=$(< image-version/version)
dir=$PWD

if [[ "${image_version}" != "${blob_version}" ]]; then
  pushd windowsfs-release/src/code.cloudfoundry.org/hydrator
    go build -o $dir/hydrate ./cmd/hydrate
  popd

  pushd windowsfs-release
    mkdir -p blobs/$FS_VERSION
    $dir/hydrate download -image cloudfoundry/windows2016fs -outputDir blobs/$FS_VERSION -tag ${image_version}

    bosh remove-blob "$FS_VERSION/windows2016fs-$blob_version.tgz"
    bosh add-blob "blobs/$FS_VERSION/windows2016fs-$image_version.tgz" "$FS_VERSION/windows2016fs-$image_version.tgz"

    rm "blobs/$FS_VERSION/windows2016fs-$image_version.tgz"
  popd
else
  echo "No new windows2016fs image version detected."
fi

cp -r ./windowsfs-release/. windowsfs-release-updated-blob/
