#! Define-Groups
groups:
- name: release
  jobs:
  - build-test-push-windows2016fs

resource_types:
- name: command-runner
  type: docker-image
  source:
    repository: us-central1-docker.pkg.dev/app-runtime-platform-wg/dockerhub-mirror/cloudfoundrydevelopers/command-runner-resource
    username: _json_key
    password: ((gcp-arp-artifact-registry-service-account-token))
    tag: latest

#! Define-Resources
resources:
- name: windowsservercore-2019
  type: docker-image
  icon: docker
  source:
    repository: mcr.microsoft.com/windows/servercore
    tag: "1809-amd64"

- name: repo
  type: git
  icon: source-branch
  source:
    branch: main
    uri: git@github.com:cloudfoundry/windows2016fs.git
    private_key: ((github-appruntimeplatform-bot/private-key))

- name: windows-worker-lock
  type: pool
  icon: cloud-lock
  source:
    branch: main
    pool: windows-worker-lock
    private_key: ((github-appruntimeplatform-bot/private-key))
    uri: git@github.com:cloudfoundry/runtime-ci-pools.git

#! MS dockerfile we can pull update URLs from
- name: dotnet-dockerfile
  type: git
  icon: source-branch
  source:
    uri: git@github.com:microsoft/dotnet-framework-docker.git
    branch: main
    private_key: ((github-appruntimeplatform-bot/private-key))
    paths:
      - src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile

#! Git for Windows Release
- name: git-setup
  type: github-release
  icon: github
  check_every: '5m'
  source:
    user: git-for-windows
    repository: git
    access_token: ((github-appruntimeplatform-bot/access-token))

- name: ci
  type: git
  icon: source-branch
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci

- name: version
  type: semver
  icon: counter
  source:
    access_key_id: ((aws-s3-svc-gdn-win-bosh-s3/access-key-id))
    secret_access_key: ((aws-s3-svc-gdn-win-bosh-s3/secret-access-key))
    assume_role_arn: ((aws-s3-svc-gdn-win-bosh-s3/assume-role))
    bucket: windows2019fs
    initial_version: 2019.0.1
    key: image-version
    region_name: us-east-1

- name: image
  type: registry-image
  icon: docker
  source:
    repository: us-central1-docker.pkg.dev/app-runtime-platform-wg/dockerhub-mirror/cloudfoundry/tas-runtime-build
    username: _json_key
    password: ((gcp-arp-artifact-registry-service-account-token))
    tag: 'latest'

#! Define-Jobs
jobs:
- name: build-test-push-windows2016fs
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: repo
    - get: image
    - get: windowsservercore-2019
      trigger: true
      params:
        save: false
        rootfs: false
        skip_download: true
    - get: dotnet-dockerfile
      trigger: true
    - get: git-setup
      params:
        globs: [Git-*-64-bit.exe]
    - get: version
      params: {bump: patch}
  - task: combine-assets
    file: ci/shared/tasks/combine-assets/linux.yml
    image: image
    input_mapping:
      input-01: repo
      input-02: git-setup
      input-03: dotnet-dockerfile
    params:
      COPY_ACTIONS: |
        {input-01/2019/Dockerfile,combined-assets}
        {input-02/Git-*-64-bit.exe,combined-assets}
        {input-03/src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile,combined-assets/dotnet-dockerfile}
  - put: windows-worker-lock
    params:
      acquire: true
  - task: start-windows-worker
    image: image
    file: ci/shared/tasks/bosh-start/linux.yml
    params:
      DEPLOYMENT: windows-worker
      INSTANCE_GROUP: windows-worker
      BOSH_CREDS: ((bosh-concourse-credentials/env_vars))
  - task: start-smb-server-vm
    image: image
    file: ci/shared/tasks/start-gcp-instance/linux.yml
    params:
      INSTANCE_NAME: garden-windows-ci-smb-server
      ZONE: us-central1-c
      PROJECT: cf-diego-pivotal
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-service-account/config-json))
  - task: build-test-push-windows2016fs
    file: ci/shared/tasks/run-bin-test/windows.yml
    input_mapping:
      built-binaries: combined-assets
      input-01: windowsservercore-2019
      input-02: version
    params:
      ENVS: |
        UPSTREAM_IMAGE_DIGEST=$PWD/input-01/digest
        VERSION_NUMBER=$PWD/input-02/number
        DOTNET_DOCKERFILE=$PWD/built-binaries/dotnet-dockerfile
        BUILT_BINARIES=$PWD/built-binaries
        IMAGE_NAME=cloudfoundry/windows2016fs
        DOCKER_USERNAME=((dockerhub-appruntimeplatform-username))
        DOCKER_PASSWORD=((dockerhub-appruntimeplatform-password))
        OS_VERSION="2019"
        SHARE_IP=((gcp-garden-windows-ci-smb-server/ip))
        SHARE_FQDN=((gcp-garden-windows-ci-smb-server/fqdn))
        SHARE_NAME=((gcp-garden-windows-ci-smb-server/share_name))
        SHARE_USERNAME=((gcp-garden-windows-ci-smb-server/username))
        SHARE_PASSWORD="((gcp-garden-windows-ci-smb-server/password))"
  - task: build-rootfs-metadata
    file: ci/windows2016fs/tasks/build-rootfs-metadata/windows.yml
  - task: add-kb-metadata
    file: ci/shared/tasks/combine-assets/linux.yml
    image: image
    input_mapping:
      input-01: repo
      input-02: built-metadata
    params:
      COPY_ACTIONS: |
        {input-01/.[^.]*,combined-assets}
        {input-01/*,combined-assets}
        {input-02/kb-metadata,combined-assets/2019/kb-metadata}
  - task: bump-repo-windows2016fs-version
    file: ci/shared/tasks/bump-repo-version-file/linux.yml
    image: image
    input_mapping:
      repo: combined-assets
    params:
      BUMP_ACTION: |
        echo ${VERSION} > 2019/IMAGE_TAG
        dos2unix 2019/kb-metadata
  - in_parallel:
    - do:
      - put: repo
        params:
          rebase: true
          repository: bumped-repo
      - put: version
        params:
          file: version/version
  ensure:
    in_parallel:
    - task: stop-windows-worker
      image: image
      file: ci/shared/tasks/bosh-stop/linux.yml
      params:
        DEPLOYMENT: windows-worker
        INSTANCE_GROUP: windows-worker
        BOSH_CREDS: ((bosh-concourse-credentials/env_vars))
      ensure:
        put: windows-worker-lock
        inputs: detect
        params:
          release: windows-worker-lock
    - task: stop-smb-server-vm
      image: image
      file: ci/shared/tasks/stop-gcp-instance/linux.yml
      params:
        INSTANCE_NAME: garden-windows-ci-smb-server
        ZONE: us-central1-c
        PROJECT: cf-diego-pivotal
        SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-service-account/config-json))
