#!/usr/bin/env bash

set -eu

mkdir -p "go/src/$IMPORT_PATH"
cp -r repo/* "go/src/$IMPORT_PATH"

export GOPATH="$PWD/go"
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOBIN"

go install github.com/onsi/ginkgo/v2/ginkgo@latest

pushd "go/src/$IMPORT_PATH"
  go get ./...
  ginkgo -p -r -race -keep-going -randomize-suites -skip-package "$IGNORE_PACKAGES"
popd
