---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: repo

run:
  path: ci/garden-windows/tasks/ginkgo-to-gopath-linux/run

params:
  IMPORT_PATH:
  NODES: 4
  IGNORE_PACKAGES:
