#@ load("@ytt:data", "data")
#@ load("ytt-helpers.star", "helpers")

#! Define-Groups
groups:
- name: release
  jobs:
  - template-tests
  - unit-and-integration-tests
  - lint-repo
  - claim-env
  - prepare-env
  - run-cats
  - <REPLACE_ME>
  - export-release
  - ship-what
  - ship-it
  - unclaim-env

- name: periodics
  jobs:
  - bump-dependencies-go-mod
  - bump-package-golang

- name: manual
  jobs:
  - release-env-lock

- name: version
  jobs:
  - major-bump
  - minor-bump
  - patch-bump


#! Define-ResourceGroups
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

#! Define-Resources
resources:
- name: golang-release-latest
  type: git
  icon: git
  source:
    tag_filter: v*
    uri: https://github.com/bosh-packages/golang-release.git

- name: repo
  type: git
  icon: git
  source:
    branch: develop
    uri: git@github.com:<REPLACE_ME>
    private_key: ((github-appruntimeplatform-bot/private-key))
    ignore_paths:
    - .github/
    - .gitignore
    - .final_build
    - CODEOWNERS
    - LICENSE
    - NOTICE
    - README.md
    - docs/
    - releases/

#! repo-synced is a write-only resource to prevent readme
#! changes from triggering pipeline runs. See the description of "ignore_path"
#! here for more info: https://github.com/concourse/git-resource
- name: repo-synced
  type: git
  icon: git
  source:
    branch: develop
    uri: git@github.com:<REPLACE_ME>
    private_key: ((github-appruntimeplatform-bot/private-key))

- name: release-branch
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/<REPLACE_ME>.git
    branch: release
    private_key: ((github-appruntimeplatform-bot/private-key))

- name: develop-branch-mergeback
  type: git
  icon: git
  source:
    uri: git@github.com:cloudfoundry/<REPLACE_ME>.git
    branch: develop
    private_key: ((github-appruntimeplatform-bot/private-key))

- name: ci
  type: git
  icon: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci

- name: cf-deployment
  type: git
  icon: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: cf-deployment-concourse-tasks
  type: git
  icon: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: cf-acceptance-tests
  type: git
  icon: git
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-acceptance-tests

- name: go-version
  type: git
  icon: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/wg-app-platform-runtime-ci
    paths: [go-version.json]

#! TIMERS
- name: weekly
  type: time
  icon: clock
  source:
    interval: '168h'
    #! - wg-*-modules pipelines should run at 00:00 to 00:59 on unique days from other wg-*-modules pipelines
    #!   all boshreleases in a WG should run independently at different hours, on the same day that its
    #!   wg-*-modules pipeline ran. For example, wg-arp-garden runs on the following schedule:
    #!     wg-arp-garden-modules:    Wednesdays at 00:00 to 00:59
    #!     envoy-nginx-release:      Wednesdays at 01:00 to 01:59
    #!     garden-runc-release:      Wednesdays at 02:00 to 02:59
    #!     winc-release:             Wednesdays at 03:00 to 03:59
    #!     windowsfs-online-release: Wednesdays at 04:00 to 04:59
    #!     windows2019fs-release:    Wednesdays at 05:00 to 05:59
    #! - This is done to ensure we don't overwhelm concourse all at once with these periodic checks, to allow us
    #!   to keep worker counts lower.
    start: 01:00
    stop: 01:59
    days:
      - Monday

- name: slack-ci-channel
  type: slack-notification
  source:
    url: ((slack-ci-channel/webhook))

- name: env
  type: git
  icon: sheep
  source:
    branch: main
    uri: git@github.com:cloudfoundry/app-runtime-platform-envs
    private_key: ((github-appruntimeplatform-bot/private-key))
    paths:
      - <REPLACE_ME>

- name: github-release
  type: github-release
  icon: github
  source:
    access_token: ((github-appruntimeplatform-bot/access-token))
    repository: <REPLACE_ME>
    owner: cloudfoundry

- name: draft-github-release
  type: github-release
  icon: github
  source:
    access_token: ((github-appruntimeplatform-bot/access-token))
    drafts: true
    repository: <REPLACE_ME>
    owner: cloudfoundry

- name: version
  type: semver
  icon: counter
  source:
    driver: gcs
    bucket: ci-release-versions
    key: <REPLACE_ME>/version
    json_key: ((gcp-wg-arp-oss-service-account/config-json))

- name: env-lock
  type: pool
  icon: cloud-lock
  source:
    branch: main
    pool: <REPLACE_ME>-env-lock
    private_key: ((github-appruntimeplatform-bot/private-key))
    uri: git@github.com:cloudfoundry/runtime-ci-pools.git

- name: image
  type: registry-image
  icon: docker
  source:
    repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/cloudfoundry/tas-runtime-build
    username: _json_key
    password: ((gcp-wg-arp-service-account/config-json))
    tag: 'latest'

#! Define-Jobs
jobs:
- name: bump-dependencies-go-mod
  serial: true
  on_failure: &ci-notification
    put: slack-ci-channel
    params:
      text: ":concourse-failed: $BUILD_PIPELINE_NAME failed on <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_JOB_NAME>."
  plan:
  - in_parallel:
      steps:
      - get: ci
      - get: repo
      - get: image
      - get: weekly
        trigger: true
  - task: <REPLACE_ME>-bump-dependencies-go-mod
    image: image
    file: ci/shared/tasks/bump-dependencies-go-mod/linux.yml
    params:
      GO_MODS: |
        <REPLACE_ME>
  - put: repo
    params:
      rebase: true
      repository: bumped-repo

- name: bump-package-golang
  on_failure: *ci-notification
  plan:
  - in_parallel:
    - get: ci
    - get: repo
    - get: image
    - get: go-version
      trigger: true
    - get: golang-release-latest
      trigger: true

  - task: bump-golang-package-name
    image: image
    file: ci/shared/tasks/bump-golang-package-name/linux.yml
    output_mapping:
      bumped-repo: bumped-golang-package-name-linux
    params:
      PLATFORM: linux

  - task: bump-golang-linux
    file: ci/shared/tasks/bosh-vendor-package/linux.yml
    image: image
    input_mapping:
      repo: bumped-golang-package-name-linux
      package-release: golang-release-latest
    params:
      PACKAGE_NAME: golang-*-linux
      AWS_ACCESS_KEY_ID: ((aws-s3-garden-linux-release/access-key-id))
      AWS_SECRET_ACCESS_KEY: ((aws-s3-garden-linux-release/secret-access-key))

  - put: repo
    params:
      rebase: true
      repository: vendored-repo

- name: template-tests
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: repo
      trigger: true
    - get: image
  - task: template-tests
    image: image
    file: ci/shared/tasks/run-tests-templates/linux.yml
    timeout: 30m

- name: unit-and-integration-tests
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: repo
      trigger: true
    - get: image
    - get: package-release
      resource: golang-release-latest
  - task: determine-image-tag
    image: image
    file: ci/shared/tasks/determine-image-tag/linux.yml
  - load_var: image_tag
    file: determined-image-tag/tag
  - task: build-binaries
    file: ci/shared/tasks/build-binaries/linux.yml
    params:
      DEFAULT_PARAMS: "ci/<REPLACE_ME>/default-params/build-binaries/linux.yml"
    vars:
      image_repository: cloudfoundry/tas-runtime-build
      image_password: ((gcp-wg-arp-service-account/config-json))
      image_tag: ((.:image_tag))
  - in_parallel:
#@ for repo in data.values.internal_repos:
    - task: #@ "{}".format(repo)
      file: ci/shared/tasks/run-bin-test/linux.yml
      vars:
        image_repository: cloudfoundry/tas-runtime-build
        image_password: ((gcp-wg-arp-service-account/config-json))
        image_tag: ((.:image_tag))
      params:
        DIR: #@ "src/code.cloudfoundry.org/{}".format(repo)
        DEFAULT_PARAMS: "ci/<REPLACE_ME>/default-params/run-bin-test/linux.yml"
#@ end

- name: lint-repo
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: repo
      trigger: true
    - get: image
  - task: lint-repo
    file: ci/shared/tasks/lint-repo/linux.yml
    image: image

- name: claim-env
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: repo
      trigger: true
      passed:
        - template-tests
        - unit-and-integration-tests
        - lint-repo
    - get: image
    - get: env
    - put: env-lock
      params:
       acquire: true
  - task: start-bbl-envs
    image: image
    file: ci/shared/tasks/start-gcp-instance/linux.yml
    input_mapping:
      bbl-state: env
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-ci-bbl-service-account/config-json))
      BBL_STATE_DIR: <REPLACE_ME>
      RESUME: true
  - task: wait-for-bosh-api
    image: image
    file: ci/shared/tasks/wait-for-bosh-api/linux.yml
    params:
      BBL_STATE_DIR: <REPLACE_ME>

- name: prepare-env
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: repo
      trigger: true
      passed: [claim-env]
    - get: image
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: env
      passed: [claim-env]
      trigger: true
  - try:
      do:
        - task: bosh-deld
          image: image
          file: ci/shared/tasks/bosh-deld/linux.yml
          params:
            BBL_STATE_DIR: <REPLACE_ME>
            DEPLOYMENT_NAME: cf
  - task: prepare-cf-deployment-env
    image: image
    file: ci/shared/tasks/run-bin-prepare-cf-deployment-env/linux.yml
    params:
      BBL_STATE_DIR: <REPLACE_ME>
      FUNCTIONS: "ci/<REPLACE_ME>/helpers/helpers.bash"
  - task: combine-ops-files
    file: ci/shared/tasks/combine-assets/linux.yml
    image: image
    input_mapping:
      input-01: cf-deployment
    params:
      COPY_ACTIONS: |
        {input-01/operations/use-compiled-releases.yml,combined-assets}
        <REPLACE_ME>
  - task: deploy-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      ops-files: combined-assets
      vars-files: prepared-env
      bbl-state: env
    params:
      BBL_STATE_DIR: <REPLACE_ME>
      SYSTEM_DOMAIN: <REPLACE_ME>.arp.cloudfoundry.org
      DEPLOY_WITH_UPTIME_MEASUREMENTS: "false"
      FAIL_ON_DOWNTIME: "false"
      VARS_FILES: vars.yml
      OPS_FILES: #@ "\n".join(data.values.opsfiles)
  - task: prepare-cf-deployment-env-with-cf-vars
    image: image
    file: ci/shared/tasks/run-bin-prepare-cf-deployment-env/linux.yml
    params:
      BBL_STATE_DIR: <REPLACE_ME>
  - task: uptimer-measure-with-<REPLACE_ME>-update
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      ops-files: combined-assets
      release: repo
      vars-files: prepared-env
      bbl-state: env
    params:
      BBL_STATE_DIR: <REPLACE_ME>
      SYSTEM_DOMAIN: <REPLACE_ME>.arp.cloudfoundry.org
      TCP_DOMAIN: tcp.<REPLACE_ME>.arp.cloudfoundry.org
      DEPLOY_WITH_UPTIME_MEASUREMENTS: "true"
      APP_PUSHABILITY_THRESHOLD: "20"
      APP_STATS_THRESHOLD: "20"
      HTTP_AVAILABILITY_THRESHOLD: "20"
      TCP_AVAILABILITY_THRESHOLD: "20"
      AVAILABLE_PORT: "-1"
      TCP_PORT: "1029"
      FAIL_ON_DOWNTIME: "true"
      MEASURE_SYSLOG_AVAILABILITY: "false"
      MEASURE_TCP_AVAILABILITY: "true"
      RECENT_LOGS_THRESHOLD: "50"
      STREAMING_LOGS_THRESHOLD: "50"
      APP_SYSLOG_AVAILABILITY_THRESHOLD: "50"
      USE_SINGLE_APP_INSTANCE: "false"
      VARS_FILES: vars.yml
      OPS_FILES: #@ "\n".join(data.values.opsfiles)
  - task: open-asg-for-credhub
    file: cf-deployment-concourse-tasks/open-asgs-for-bosh-instance-group/task.yml
    input_mapping:
      bbl-state: env
    params:
      BBL_STATE_DIR: <REPLACE_ME>
      SYSTEM_DOMAIN: <REPLACE_ME>.arp.cloudfoundry.org
      INSTANCE_GROUP_NAME: credhub
      SECURITY_GROUP_NAME: credhub
  - task: open-asg-for-uaa
    file: cf-deployment-concourse-tasks/open-asgs-for-bosh-instance-group/task.yml
    input_mapping:
      bbl-state: env
    params:
      BBL_STATE_DIR: <REPLACE_ME>
      SYSTEM_DOMAIN: <REPLACE_ME>.arp.cloudfoundry.org
      INSTANCE_GROUP_NAME: uaa
      SECURITY_GROUP_NAME: uaa
  - task: enable-feature-flags-for-cats
    file: cf-deployment-concourse-tasks/set-feature-flags/task.yml
    input_mapping:
      bbl-state: env
    params:
      BBL_STATE_DIR: <REPLACE_ME>
      SYSTEM_DOMAIN: <REPLACE_ME>.arp.cloudfoundry.org
      ENABLED_FEATURE_FLAGS: diego_docker service_instance_sharing

- name: run-cats
  serial: true
  serial_groups: [acceptance]
  plan:
  - in_parallel:
    - get: ci
    - get: repo
      passed: [prepare-env]
      trigger: true
    - get: image
    - get: env
      passed: [prepare-env]
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: cf-acceptance-tests
    - get: cf-deployment
  - task: create-cats-config
    image: image
    file: ci/shared/tasks/build-acceptance-test-configs/linux.yml
    params:
      BBL_STATE_DIR: <REPLACE_ME>
      CONFIGS: cats
      WITH_ISOSEG: true
      WITH_DYNAMIC_ASG: true
  - task: cats
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    attempts: 2
    input_mapping:
      integration-config: built-acceptance-test-configs
    params:
      CONFIG_FILE_PATH: cats.json

- name: export-release
  serial: true
  serial_groups: [acceptance]
  plan:
  - in_parallel:
    - get: ci
    - get: repo
      passed: [prepare-env]
      trigger: true
    - get: image
    - get: env
      passed: [prepare-env]
      trigger: true
    - get: cf-deployment-concourse-tasks
  - task: export-release
    file: ci/shared/tasks/bosh-export-release/linux.yml
    image: image
    params:
      BBL_STATE_DIR: <REPLACE_ME>

- name: ship-what
  on_success:
    put: slack-ci-channel
    params:
      text: ":concourse-succeeded: $BUILD_PIPELINE_NAME ship-what just ran. Maybe you should cut a release? $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME"
  plan:
    - in_parallel:
        steps:
        - get: ci
        - get: repo
          passed:
            - run-cats
            - <REPLACE_ME>
            - export-release
          trigger: true
        - get: image
        - get: release-branch
          params:
            submodules: none
        - get: github-release
        - get: version
        - get: env
          passed:
            - run-cats
            - <REPLACE_ME>
            - export-release
          trigger: true

    - task: check-safe-to-release-repo
      image: image
      file: ci/shared/tasks/check-safe-to-release-repo/linux.yml
      input_mapping:
        release-repo: release-branch

    - task: build-release-notes-<REPLACE_ME>
      image: image
      file: ci/shared/tasks/build-release-notes/linux.yml
      input_mapping:
        previous-github-release: github-release

- name: ship-it
  serial: true
  plan:
    - in_parallel:
        steps:
        - get: ci
        - get: repo
          passed: [ ship-what ]
        - get: image
        - get: release-branch
          params:
            submodules: none
        - get: github-release
        - get: version
        - get: develop-branch-mergeback
          params:
            submodules: none

    - task: check-safe-to-release-branch
      image: image
      file: ci/shared/tasks/check-safe-to-release-repo/linux.yml
      input_mapping:
        release-repo: release-branch

    - task: build-release-notes-<REPLACE_ME>
      image: image
      file: ci/shared/tasks/build-release-notes/linux.yml
      input_mapping:
        previous-github-release: github-release

    - task: bosh-finalize-release
      image: image
      file: ci/shared/tasks/bosh-finalize-release/linux.yml
      params:
        GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-oss-service-account/config-json))

    - put: release-branch
      params:
        repository: finalized-release-repo
        tag: version/number
        tag_prefix: v

    - task: merge-release-onto-develop
      image: image
      file: ci/shared/tasks/git-merge-branches/linux.yml
      input_mapping:
        source-branch: release-branch
        onto-branch: develop-branch-mergeback
      params:
        SOURCE_BRANCH_NAME: <REPLACE_ME> or release
        ONTO_BRANCH_NAME: <REPLACE_ME> or develop

    - in_parallel:
        steps:
        - put: draft-github-release
          params:
            name: version/number
            tag: version/number
            tag_prefix: v
            body: built-release-notes/notes.md
            globs:
            - finalized-release-tarball/<REPLACE_ME>*.tgz
        - put: develop-branch-mergeback
          params:
            repository: merged-branch
            merge: true

    - get: next-version
      resource: version
      params: {bump: minor}
    - put: next-version
      resource: version
      params: {file: next-version/number}

- name: unclaim-env
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: env
        passed: [ship-what]
        trigger: true
      - get: image
      - get: env-lock
      - get: ci
  - task: bosh-deld
    image: image
    file: ci/shared/tasks/bosh-deld/linux.yml
    params:
      BBL_STATE_DIR: <REPLACE_ME>
      DEPLOYMENT_NAME: cf
  - put: env-lock
    params:
      release: env-lock #! path to the resource in the above get
  - task: stop-bbl-envs
    image: image
    file: ci/shared/tasks/stop-gcp-instance/linux.yml
    input_mapping:
      bbl-state: env
    params:
      SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-ci-bbl-service-account/config-json))
      BBL_STATE_DIR: <REPLACE_ME>
      SUSPEND: true

- name: release-env-lock
  plan:
  - in_parallel:
      steps:
      - get: env-lock
      - get: env
      - get: ci
      - get: image
  - try:
      do:
      - task: bosh-deld
        image: image
        file: ci/shared/tasks/bosh-deld/linux.yml
        params:
          BBL_STATE_DIR: <REPLACE_ME>
          DEPLOYMENT_NAME: cf
  - try:
      do:
      - task: stop-bbl-envs
        image: image
        file: ci/shared/tasks/stop-gcp-instance/linux.yml
        input_mapping:
          bbl-state: env
        params:
          SERVICE_ACCOUNT_KEY: ((gcp-wg-arp-ci-bbl-service-account/config-json))
          BBL_STATE_DIR: <REPLACE_ME>
          SUSPEND: true
  ensure:
    put: env-lock
    params:
      release: env-lock #! path to the resource in the above get


#! versioning
- name: patch-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: patch}
  - put: version
    params: {file: version/number}

- name: minor-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: major-bump
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major}
  - put: version
    params: {file: version/number}
