#!/usr/bin/env bash

set -e

pushd windowsfs-release
  ./scripts/create-release --tarball ../release-tarball/release.tgz --timestamp-version
popd
mkdir release-tarball/config
cp windowsfs-release/config/final.yml release-tarball/config
echo "release.tgz" > release-tarball/name
