---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: windowsfs-release

outputs:
- name: release-tarball

run:
  path: ci/garden-windows/tasks/create-fs-release-linux/run
