#!/bin/bash

set -e -x -u

pushd ${PWD}/deployments-diego/${DEPLOYMENT_DIR}
source .envrc
popd

bosh -n clean-up

# delete orphaned disks
bosh disks --orphaned | grep -E "disk-|vol-" | cut -d' ' -f2 | xargs -r -n1 bosh -n delete-disk
