#!/usr/bin/env bash

set -ex

export BOSH_ENVIRONMENT
export BOSH_CLIENT
export BOSH_CLIENT_SECRET

export DEPLOYMENT_DIR="${PWD}/deployments-diego/${DEPLOYMENT_DIR}"
export BOSH_CA_CERT="${DEPLOYMENT_DIR}/certs/bosh-ca.crt"

bosh log-in

for deployment in $DEPLOYMENTS; do
  bosh -n -d $deployment delete-deployment
done

