#!/usr/bin/env bash

set -ex

: ${RELEASE_NAME:?must be provided}
: ${DEPLOYMENT_DIR:?must be provided}

export BOSH_DEPLOYMENT=${BOSH_DEPLOYMENT:-cf}

export DEPLOYMENT_DIR="${PWD}/deployments-diego/${DEPLOYMENT_DIR}"

pushd ${DEPLOYMENT_DIR}
  source .envrc
popd

STEMCELL_NAME_AND_VERSION=$( bosh stemcells --json | jq -r '.Tables[0].Rows[] | .os+"/"+.version' | grep ubuntu | tr -d "*")
RELEASE_VERSION=$(bosh deployment -d cf --json | jq -r .Tables[0].Rows[0].release_s | grep ${RELEASE_NAME} | cut -d'/' -f2)

bosh log-in

bosh export-release ${RELEASE_NAME}/${RELEASE_VERSION} ${STEMCELL_NAME_AND_VERSION}
