#!/usr/bin/env bash

set -ex

export BOSH_ENVIRONMENT
export BOSH_CLIENT
export BOSH_CLIENT_SECRET
export BOSH_DEPLOYMENT

export DEPLOYMENT_DIR="${PWD}/deployments-diego/${DEPLOYMENT_DIR}"
export BOSH_CA_CERT="${DEPLOYMENT_DIR}/certs/bosh-ca.crt"

STEMCELL_VERSION=$(cat aws-stemcell/version)
RELEASE_VERSION=$(cat diego-release-tarball/version)

bosh log-in

bosh export-release --dir=exported-release ${RELEASE_NAME}/${RELEASE_VERSION} ubuntu-trusty/${STEMCELL_VERSION}
