#!/usr/bin/env bash

set -ex

export DEPLOYMENT_DIR="${PWD}/deployments-diego/${DEPLOYMENT_DIR}"

cd $DEPLOYMENT_DIR
source .envrc

bosh log-in

for deployment in $DEPLOYMENTS; do
  bosh -n -d $deployment delete-deployment
done

