#!/usr/bin/env bash

set -ex

: ${RELEASE_NAME:?must be provided}
: ${DEPLOYMENT_DIR:?must be provided}

export BOSH_DEPLOYMENT=${BOSH_DEPLOYMENT:-cf}

export DEPLOYMENT_DIR="${PWD}/deployments-diego/${DEPLOYMENT_DIR}"

STEMCELL_VERSION=$(cat gcp-stemcell/version)
RELEASE_VERSION=$(cat diego-release-tarball/version)

pushd ${DEPLOYMENT_DIR}
  source .envrc
popd

bosh log-in

bosh export-release --dir=exported-release ${RELEASE_NAME}/${RELEASE_VERSION} ubuntu-trusty/${STEMCELL_VERSION}
