#!/bin/bash

set -e -x

WORKDIR=$PWD

TAG=v$(cat garden-linux-release-tarball/version)

# switch release repo to tag determined by tarball version
pushd garden-linux-release-master
  git fetch --tags
  git checkout $TAG
  git submodule update --init --recursive
popd

# unmount everything in $WORKDIR so we can nuke it later
cat /proc/mounts | grep $WORKDIR | awk {'print $2'} | xargs umount

mv garden-linux-release-master /tmp/garden-linux-repo
cd /

# $WORKDIR becomes garden-linux-repo
mv /tmp/garden-linux-repo $WORKDIR
