#!/bin/bash

set -e -x

WORKDIR=$PWD

TAG=v$(cat garden-linux-release-tarball/version)

# switch release repo to tag determined by tarball version
pushd garden-linux-release-master
  git fetch --tags
  git checkout $TAG
  git submodule update --init --recursive
popd

cp -r garden-linux-release-master/. garden-linux-release
