#!/bin/bash

set -e -x

WORKDIR=$PWD

TAG=v$(cat routing-release-tarball/version)

# switch release repo to tag determined by tarball version
pushd routing-release
  git fetch --tags
  git checkout $TAG
  git submodule update --init --recursive
popd
