#!/bin/bash

set -e -x -u

envs=("diego-1" "diego-2")
for DEPLOYMENT_ENV in ${envs[@]}; do
   pushd ${PWD}/deployments-diego/${DEPLOYMENT_ENV}
   source .envrc
   popd

   VM_COUNT=$(bosh -d cf vms --json | jq -r ".Tables[]?.Rows[] | .ips" | wc -l)

   if [[ $VM_COUNT -gt 0 ]]
   then
      echo "you need to clean up ... there are ${VM_COUNT} instances"
      curl -X POST --data-urlencode "payload={\"mrkdwn\": true, \"text\": \"This is a reminder that *${DEPLOYMENT_ENV}* has some VMs running...please stop them if you are not currently using the environment\"}" $SLACK_URL
   fi
done
