#!/bin/bash

set -e -x -u

$(dirname $0)/bosh_setup

manifest=/tmp/diego.yml
key=${DEPLOYMENTS_DIR}/${ENVIRONMENT}/keypair/id_rsa_bosh
bosh -n download manifest ${DIEGO_DEPLOYMENT} $manifest

function run_command_on_cell {
  command=$1
  bosh -d $manifest ssh \
       --gateway_host ${BOSH_TARGET} \
       --gateway_user vcap \
       --gateway_identity_file $key \
       cell_z1/0 \
       "$command"
}

function get_directory_stats {
  directory=$1
  run_command_on_cell "ls -dl $directory" 2>&1 | grep instance_identity | grep -v ls\ -dl | awk '{print $1,$3,$4}'
}
stats=$(get_directory_stats /var/vcap/data/executor/instance_identity)
permissions=$(echo $stats | cut -d' ' -f1)
owner_user=$(echo $stats | cut -d' ' -f2)
owner_group=$(echo $stats | cut -d' ' -f3)

fail=false
# assert that the instance_identity directory is owned by vcap and vcap is the
# only user with read/write permissions
if [ $permissions != 'drwx------' ]; then
    fail=true
    echo "File permissions are too open"
fi
if [ $owner_group != 'vcap' ]; then
    fail=true
    echo "File is not owned by vcap group"
fi
if [ $owner_user != 'vcap' ]; then
    fail=true
    echo "File is not owned by vcap user"
fi

if [ "x$fail" = "xtrue" ]; then
    echo "stats: $stats"
    exit 1
fi
