#!/bin/bash

set -e -x

cd diego-release
bosh sync-blobs

cd blobs/proxy
tar -xf envoy*.tgz

filename_version=$(ls -1 envoy*.tgz | xargs basename | sed 's/envoy-\(.*\).tgz/\1/g')
actual_version=$(./envoy --version | grep -vE '^$' | awk '{print $3}' | cut -d/ -f1)

if [ "x$filename_version" != "x$actual_version" ]; then
    echo "Expected $filename_version in $(ls -1 diego-release/blobs/prxoy/envoy*.tgz) to match $actual_version"
    exit 1
fi
exit 0
