#!/bin/bash

set -e -x

cp /usr/local/bin/envoy envoy-binary
pushd envoy-binary
  tar -czf envoy.tgz envoy
popd

cp -r diego-release-old-envoy/* diego-release
cp envoy-binary/envoy.tgz diego-release/blobs/proxy
