#!/bin/bash

set -e -x

cp /usr/local/bin/envoy $PWD/envoy-binary/

repository_version=$(envoy --version | tr -d '\n' | awk '{print $3}' | cut -d/ -f1)

apt-get update
apt-get install -y wget

wget -O $PWD/envoy-binary/LICENSE https://raw.githubusercontent.com/envoyproxy/envoy/${repository_version}/LICENSE
wget -O $PWD/envoy-binary/NOTICE https://raw.githubusercontent.com/envoyproxy/envoy/${repository_version}/NOTICE

pushd envoy-binary
  tar -czf envoy.tgz envoy LICENSE NOTICE
popd
