#!/bin/bash

set -e -x

cp /usr/local/bin/envoy $PWD/envoy-binary/

repository_version=$(envoy --version | tr -d '\n' | awk '{print $3}' | cut -d/ -f1)

apt-get update
apt-get install -y wget

wget -O WORKSPACE https://raw.githubusercontent.com/istio/proxy/${repository_version}/WORKSPACE

envoy_version=$(grep "ENVOY_SHA =" WORKSPACE | tr -d '\n' | awk '{print $3}')

wget -O $PWD/envoy-binary/LICENSE https://raw.githubusercontent.com/istio/envoy/${envoy_version}/LICENSE
wget -O $PWD/envoy-binary/NOTICE https://raw.githubusercontent.com/istio/envoy/${envoy_version}/NOTICE

pushd envoy-binary
  tar -czf envoy.tgz envoy LICENSE NOTICE
popd
