#!/usr/bin/env bash

set -ex

pushd deployments-diego/${DEPLOYMENT_DIR}/
  source .envrc
popd
export BOSH_DEPLOYMENT

export DIEGO_RELEASE="${PWD}/diego-release"
export BOSH_MANIFEST="${PWD}/merged-cf-deployment/cf-deployment.yml"
export OPSFILE_DIR="${PWD}/merged-cf-deployment/operations"

export DEPLOYMENT_DIR="${PWD}/deployments-diego/${DEPLOYMENT_DIR}"
export BOSH_CA_CERT="${DEPLOYMENT_DIR}/deployments/bbl/ca-cert"

deployments_var_file="${DEPLOYMENT_DIR}/cf-deployment-vars.yml"
deployment_file="${DEPLOYMENT_DIR}/cf.yml"

bosh log-in
bosh -n upload-stemcell bosh-stemcell/*.tgz

if [ "${USE_POSTGRES}" == "true" ]; then
  postgres_ops_files="-o ${OPSFILE_DIR}/test/add-datadog-firehose-nozzle.yml \
    -o ${OPSFILE_DIR}/use-postgres.yml \
    -o ${OPSFILE_DIR}/use-latest-stemcell.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/bbs-benchmark.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/bbs-benchmark-postgres.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/overrides.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/postgres.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/rename-deployment-postgres.yml"
  bosh -n interpolate \
    --var-errs \
    --vars-file=${deployments_var_file} ${BOSH_MANIFEST} \
    ${postgres_ops_files} \
    -o <(cat <<EOF
- type: replace
  path: /releases/name=diego
  value:
    name: diego
    version: create
    url: file://${DIEGO_RELEASE}
EOF
) > ${deployment_file}

  bosh  -d time_rotor_gcp_postgres -n deploy --no-redact ${deployment_file}
else
  ops_files="-o ${OPSFILE_DIR}/test/add-datadog-firehose-nozzle.yml \
    -o ${OPSFILE_DIR}/use-latest-stemcell.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/bbs-benchmark.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/overrides.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/mysql.yml \
    -o ${DIEGO_RELEASE}/operations/benchmark-gcp/rename-deployment.yml"

  bosh -n interpolate \
    --var-errs \
    --vars-file=${deployments_var_file} ${BOSH_MANIFEST} \
    ${ops_files} \
    -o <(cat <<EOF
- type: replace
  path: /releases/name=diego
  value:
    name: diego
    version: create
    url: file://${DIEGO_RELEASE}
EOF
) > ${deployment_file}

  bosh  -d time_rotor_gcp -n deploy --no-redact ${deployment_file}
fi
