#!/bin/bash

set -ex

bosh --version

pushd $DEPLOYMENTS_DIR/$ENVIRONMENT_NAME
  source .envrc
popd

environment_dir=$DEPLOYMENTS_DIR/$ENVIRONMENT_NAME
stubs_dir=${environment_dir}/stubs
deployments_dir=${environment_dir}/deployments

bosh -n update-cloud-config ${stubs_dir}/cloud-config.yml ${cloud_config_flags}
bosh interpolate cf-mysql-deployment/cf-mysql-deployment.yml \
     --var-errs \
     --vars-file ${deployments_dir}/cf-mysql-vars.yml \
     --vars-file ${stubs_dir}/cf-mysql/consul-secrets.yml \
     -o cf-mysql-deployment/operations/proxy-consul.yml \
     -o ${stubs_dir}/cf-mysql/mysql-overrides-ops.yml > manifest.yml

bosh -n -d cf-${ENVIRONMENT_NAME}-mysql deploy --no-redact manifest.yml
