#!/bin/bash

set -e -x

setup_env() {
  export ENV_DIR="$PWD/${DEPLOYMENTS_DIR}/${ENVIRONMENT}/${BOSH_LITE_NAME}"
  export BOSH_DEPLOYMENT_DIR="$PWD/bosh-deployment"
  export GCP_CREDENTIALS_PATH="${ENV_DIR}/cf-diego.json"
  export BOSH_LITE_PRIVATE_KEY="$PWD/${DEPLOYMENTS_DIR}/${ENVIRONMENT}/keypair/dusts"
}

deprovision_bosh_lite () {
  bosh2 delete-env ${BOSH_DEPLOYMENT_DIR}/bosh.yml \
    --state ${ENV_DIR}/state.json \
    -o ${BOSH_DEPLOYMENT_DIR}/gcp/cpi.yml \
    -o ${ENV_DIR}/operations/increase-instance-size.yml \
    -o ${BOSH_DEPLOYMENT_DIR}/bosh-lite.yml \
    --vars-file ${ENV_DIR}/creds.yml \
    --vars-env BOSH_LITE \
    --vars-env GCP \
    -v tags=["bosh-lite","${BOSH_LITE_NAME}"] \
    --var-file gcp_credentials_json=${GCP_CREDENTIALS_PATH} \
    -o ${BOSH_DEPLOYMENT_DIR}/external-ip-not-recommended.yml
}

commit_state_json() {
  pushd $PWD/${DEPLOYMENTS_DIR}
    git config user.email "cf-diego@pivotal.io"
    git config user.name "CI (Automated)"

    git add -A
    git commit -m "Deprovision dusts deployment ${BOSH_LITE_NAME}"
  popd
}

main() {
  setup_env
  if [ -f ${ENV_DIR}/state.json ]; then
    deprovision_bosh_lite
    commit_state_json
  else
    echo "No bosh-lite to deprovision"
  fi

  cp -a $PWD/${DEPLOYMENTS_DIR} deprovisioned-bosh-lite/
}

main
