#!/bin/bash
set -e -x

source ~/.bashrc

export WORKSPACE_DIR="$(pwd)"
export ENV_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}/${ENVIRONMENT}"

source $ENV_DIR/bootstrap_environment

instances=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${BOSH_LITE_NAME}" \
  --output text --query 'Reservations[*].Instances[*].InstanceId')

echo $instances | \
  tr '\n' ' ' > instances-to-delete

if [ -s instances-to-delete ]
then
  instance_id=$(cat instances-to-delete)
  public_ip=$(aws ec2 describe-addresses --filters "Name=instance-id,Values=${instance_id}" | jq '.Addresses[0].PublicIp' -r)

  echo "Deleting instances: ${instance_id}"

  aws ec2 terminate-instances --instance-ids ${instance_id}
  aws ec2 wait instance-terminated --instance-ids ${instance_id}

  if [ ${public_ip} != "null" ]; then
    aws ec2 release-address --public-ip ${public_ip}
  fi
else
  echo "No instances to delete"
fi
