#!/bin/bash

set -e -x -u


for i in $(seq 10); do
  echo "Attempt #${i}"

  if cf api --skip-ssl-validation $CF_TARGET; then
    break
  fi

  sleep 1
done

cf auth $CF_USER $CF_PASSWORD

# list existing feature flags
cf feature-flags

cf enable-feature-flag diego_docker || true
