#!/bin/bash

set -e -x -u

cf api --skip-ssl-validation $CF_TARGET

set +x
echo "cf auth <redacted> <redacted>"
cf auth $CF_USER $CF_PASSWORD
set -x

# list existing feature flags
cf feature-flags

cf enable-feature-flag diego_docker || true
