#!/bin/bash

set -e -x -u

deployments_file=$1
releases_file=$2
deployment_names=$3
release_name=$4

releases=""
stemcells=""

for deployment_name in $deployment_names; do
  release=$(cat ${deployments_file} \
    | jq ". \
    | map(select(.name == \"${deployment_name}\"))[0].releases \
    | map(select(.name == \"${release_name}\"))[0].version" -r \
    )
  releases="${releases}${release}\n"

  stemcell=$(cat ${deployments_file} \
    | jq ". \
    | map(select(.name == \"${deployment_name}\"))[0].stemcells[0] \
    | join(\"/\")" -r \
    )
  stemcells="${stemcells}${stemcell}\n"
done

releases=$(echo -en $releases \
          | sort \
          | uniq \
         )

num_releases=$(echo "${releases}" | wc -l | tr -d ' ')
if [ "${num_releases}" != "1" ]; then
  echo "Expected 1 unique occurrence of ${release_name} release amongst deployments, found ${num_releases}"
  exit 1
fi
release=${releases}

stemcells=$(echo -en $stemcells \
          | sort \
          | uniq \
         )

num_stemcells=$(echo "${stemcells}" | wc -l | tr -d ' ')
if [ "${num_stemcells}" != "1" ]; then
  echo "Expected 1 unique occurrence of a stemcell amongst deployments, found ${num_stemcells}"
  exit 1
fi
stemcell=${stemcells}

sha=$(cat ${releases_file} \
     | jq ". \
     | map(select(.name == \"${release_name}\"))[0].release_versions \
     | map(select(.version == \"${release}\"))[0].commit_hash" -r \
    )

echo ${release},${sha},${stemcell}
