#!/bin/bash

set -e -x -u

if [ -z "$ENVIRONMENT_NAME" ]; then
  environment_path="${PWD}/${DEPLOYMENTS_DIR}"
else
  environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
fi

stubs_path="${environment_path}/stubs"

pushd cf-release
  ./scripts/generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/cf/*.yml \
    ${stubs_path}/diego/property-overrides.yml \
    > ../generated-mysql-manifest/cf-deployment.yml
popd

pushd cf-mysql-release-release-candidate
  ./scripts/generate-deployment-manifest \
    -c ../generated-mysql-manifest/cf-deployment.yml \
    -p $stubs_path/cf-mysql/property-overrides.yml \
    -i $stubs_path/cf-mysql/iaas-settings.yml \
    -j $stubs_path/cf-mysql/job-overrides-consul.yml \
    -n $stubs_path/cf-mysql/instance-count-overrides.yml \
  | sed '/wsrep_max_ws_size/a\
  \ \ \ \ \binlog_expire_days: 5
  ' > ../generated-mysql-manifest/cf-mysql.yml
popd
