#!/bin/bash

set -e -x -u

if [ -z "$ENVIRONMENT_NAME" ]; then
  environment_path="${PWD}/${DEPLOYMENTS_DIR}"
else
  environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
fi

stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

local_route_emitters_flag=""
if [ "$USE_LOCAL_ROUTE_EMITTERS" == "true" ]; then
    local_route_emitters_flag="-R"
fi

sql_lock_flag=""
if [ "$USE_LOCKET_SQL_LOCK_FOR_BBS" == "true" ]; then
    sql_lock_flag="-Q"
fi

grootfs_flag=""
if [ "$USE_GROOTFS" == "true" ]; then
    grootfs_flag="-G"
fi

cflinux_flag=""
if [ "$USE_CFLINUX" == "true" ]; then
    cflinux_flag="-r"
fi

sql_stub="${stubs_path}/diego/diego-mysql-sql.yml "
postgres_depoy_stub=""
if [ "$DEPLOY_POSTGRES" == "true" ]; then
  postgres_depoy_stub="${stubs-path}/cf/postgres-deploy-stub.yml"
  sql_stub="${stubs_path}/diego/diego-postgres-sql.yml "
fi

pushd cf-release
  ./scripts/generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/cf/*.yml \
    ${postgres_depoy_stub} \
    > ../generated-manifest/cf-deployment.yml
popd

pushd diego-release
  cp ../generated-manifest/cf-deployment.yml /tmp/cf.yml

  ./scripts/generate-deployment-manifest \
    -c /tmp/cf.yml \
    -i ${stubs_path}/diego/iaas-settings.yml \
    -p ${stubs_path}/diego/property-overrides.yml \
    -n ${stubs_path}/diego/instance-count-overrides.yml \
    -v ${stubs_path}/diego/release-versions.yml \
    -s ${sql_stub} -x \
    ${local_route_emitters_flag} \
    ${sql_lock_flag} \
    ${grootfs_flag} \
    ${cflinux_flag} \
    > ../generated-manifest/diego-deployment.yml
popd
