#!/bin/bash

set -e -x -u

if [ -z "$ENVIRONMENT_NAME" ]; then
  environment_path="${PWD}/${DEPLOYMENTS_DIR}"
else
  environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
fi

local_route_emitters_flag=""
if [ "$USE_LOCAL_ROUTE_EMITTERS" == "true" ]; then
    local_route_emitters_flag="-R"
fi

sql_lock_flag=""
if [ "$USE_LOCKET_SQL_LOCK" == "true" ]; then
    sql_lock_flag="-Q"
fi


stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

pushd cf-release
  ./scripts/generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/cf/*.yml \
    ${stubs_path}/diego/property-overrides.yml \
    > ../generated-manifest/cf-deployment.yml
popd

pushd diego-release
  cp ../generated-manifest/cf-deployment.yml /tmp/cf.yml

  ./scripts/generate-windows-cell-deployment-manifest \
    -c /tmp/cf.yml \
    -i ${stubs_path}/diego-windows/iaas-settings.yml \
    -p ${stubs_path}/diego-windows/property-overrides.yml \
    -n ${stubs_path}/diego-windows/instance-count-overrides.yml \
    -v ${stubs_path}/diego-windows/release-versions.yml \
    ${local_route_emitters_flag} \
    ${sql_lock_flag} \
    > ../generated-manifest/diego-windows-deployment.yml
popd
