#!/bin/bash

set -e -x -u

pushd cf-mysql-release-release-candidate
  bosh -n --parallel 10 create release --with-tarball
  cp dev_releases/cf-mysql/*.tgz ../generated-mysql-release-tarball/cf-mysql-release.tgz
popd
