#!/bin/bash

set -e -x -u

if [ -z "$ENVIRONMENT_NAME" ]; then
  environment_path="${PWD}/${DEPLOYMENTS_DIR}"
else
  environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
fi

stubs_path="${environment_path}/stubs"
manifest_path="${PWD}/generated-manifest"
templates_path="${environment_path}/templates"

diego-ci/concourse/generate_deployment_manifests

stubs="${stubs_path}/routing/iaas-settings.yml"
stubs="${stubs},${stubs_path}/routing/property-overrides.yml"
stubs="${stubs},${stubs_path}/routing/instance-count-overrides.yml"
stubs="${stubs},${stubs_path}/routing/persistent-disk-overrides.yml"

pushd routing-release
./scripts/generate-manifest \
  -c ${manifest_path}/cf-deployment.yml \
  -d ${manifest_path}/diego-deployment.yml \
  -l ${stubs} \
  > ${manifest_path}/routing-deployment.yml
popd
