#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

CF_DEPLOYMENT_NAME=${CF_DEPLOYMENT_NAME:-"cf-${ENVIRONMENT_NAME}"}

$(dirname $0)/bosh_setup

bosh download manifest ${CF_DEPLOYMENT_NAME} > /tmp/cf.yml

pushd diego-release
  if [ ! -f ${stubs_path}/vizzini/iaas-settings.yml ]; then
    spiff merge \
      manifest-generation/misc-templates/aws-iaas-settings.yml \
      ${templates_path}/diego/iaas-settings-internal.yml \
      ${stubs_path}/aws-resources.yml \
      /tmp/cf.yml \
      > /tmp/iaas-settings.yml
  else
    cp ${stubs_path}/vizzini/iaas-settings.yml /tmp/iaas-settings.yml
  fi

  ./scripts/generate-vizzini-manifest \
    -c /tmp/cf.yml \
    -p ${stubs_path}/vizzini/vizzini.yml \
    -i /tmp/iaas-settings.yml \
    > ../generated-manifest/vizzini.yml
popd
