#!/bin/sh

( cd diego-release-master && git rev-parse HEAD ) > commitish

echo "Diego $(cat diego-final-releases/version)" > name

# rename garden-linux release file so it's easier to identify in
# the release, otherwise it's just "release.tgz"
mv garden-linux-release-tarball/*.tgz garden-linux-$(cat garden-linux-release-tarball/version).tgz
mv etcd-release-tarball/*.tgz etcd-$(cat etcd-release-tarball/version).tgz
