#!/usr/bin/env bash

set -ex

export MERGED_CF_DEPLOYMENT=$PWD/merged-cf-deployment

pushd ${PWD}/cf-deployment
  echo "----- Set git identity"
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  git fetch origin "+refs/heads/*:refs/remotes/origin/*"

  for i in $(git branch -a | grep -e "remotes/origin/diego-[0-9]\+" | sort -t '-' -k 2 -g); do
    echo "----- Merging cf-deployment branch ${i}"
    git merge --no-edit $i
  done

  cp -r . $MERGED_CF_DEPLOYMENT
popd
