#!/usr/bin/env bash

set -e

export MERGED_CF_DEPLOYMENT=$PWD/merged-cf-deployment

pushd ${PWD}/cf-deployment-develop
  echo "----- Set git identity"
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> /etc/ssh/ssh_config
  git fetch origin "+refs/heads/*:refs/remotes/origin/*"

  echo "----- Adding cloned cf-deployment as remote"
  git remote add local-cf-deployment-diego ../cf-deployment-diego
  git fetch local-cf-deployment-diego

  echo "----- Merging cf-deployment branch diego"
  git merge --no-edit local-cf-deployment-diego/diego

  echo "----- Merging cf-deployment develop branch into diego branch"
  git checkout diego
  git merge --no-edit develop

  cp -r . $MERGED_CF_DEPLOYMENT
popd
