#!/usr/bin/env bash

set -ex

export BOSH_MANIFEST="${PWD}/patched-cf-deployment/cf-deployment.yml"
export OPSFILE_DIR="${PWD}/cf-deployment/operations"

cp -R ${OPSFILE_DIR} ${PWD}/patched-cf-deployment
pushd ${PWD}/cf-deployment
  git apply ../diego-release/cf-deployment-patch-files/*
  cp cf-deployment.yml ${BOSH_MANIFEST}
popd
