#!/bin/bash
set -e -x

source ~/.bashrc

setup_env() {
  export WORKSPACE_DIR="$(pwd)"
  export ENV_DIR="${WORKSPACE_DIR}/${DEPLOYMENTS_DIR}/${ENVIRONMENT}"

  export BOSH_LITE_PRIVATE_KEY="${ENV_DIR}/keypair/id_rsa_bosh"

  source $ENV_DIR/bootstrap_environment
  export BOSH_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  export BOSH_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

  export BOSH_LITE_ELASTIC_IP=$(aws ec2 allocate-address | jq '.PublicIp' -r)
  hosted_zone_id=$(aws route53 list-hosted-zones | jq '.HostedZones[0].Id' -r)

cat > command.json <<EOF
{
  "HostedZoneId": "${hosted_zone_id}",
  "ChangeBatch": {
      "Comment": "",
      "Changes": [
          {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                  "Name": "\\\\52.${DOMAIN}.",
                  "Type": "A",
                  "TTL": 1,
                  "ResourceRecords": [
                      {
                          "Value": "${BOSH_LITE_ELASTIC_IP}"
                      }
                  ]
              }
          }
      ]
  }
}
EOF

  command_id=$(aws route53 change-resource-record-sets --cli-input-json "$(cat command.json)" | jq ".ChangeInfo.Id" -r)
  aws route53 wait resource-record-sets-changed --id ${command_id}

  source $ENV_DIR/deployments/bosh-lite/boshlite_vagrant_env
}

provision_bosh_lite() {
  pushd bosh-lite

  BOSH_LITE_INSTANCE_TYPE="m3.2xlarge" vagrant up --provider=aws
  BOSH_LITE_IP=`vagrant ssh-config 2>/dev/null | grep HostName | awk '{print $2}'`
  echo $BOSH_LITE_IP > $WORKSPACE_DIR/bosh_lite_ip

  popd
}

main() {
  setup_env
  provision_bosh_lite
}

main
