#!/bin/bash
set -e -u

source ~/.bashrc

setup_env() {
  export WORKSPACE_DIR="$(pwd)"
  export ENV_DIR="${WORKSPACE_DIR}/deployments-runtime/${ENVIRONMENT}"

  export BOSH_LITE_PRIVATE_KEY="${ENV_DIR}/keypair/id_rsa_bosh"

  source $ENV_DIR/bootstrap_environment
  export BOSH_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  export BOSH_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

  source $ENV_DIR/deployments/bosh-lite/boshlite_vagrant_env
}

provision_bosh_lite() {
  pushd bosh-lite

  BOSH_LITE_INSTANCE_TYPE="m3.2xlarge" vagrant up --provider=aws
  BOSH_LITE_IP=`vagrant ssh-config 2>/dev/null | grep HostName | awk '{print $2}'`
  echo $BOSH_LITE_IP > $WORKSPACE_DIR/bosh_lite_ip

  popd
}

main() {
  setup_env
  provision_bosh_lite
}

main
