#!/bin/bash

set -e -x -u

cf api ${API} --skip-ssl-validation

cf auth ${USER} ${PASSWORD}

cf create-org ${ORG}
cf target -o ${ORG}

cf create-space ${SPACE}
cf target -s ${SPACE}

export APP_NAME=${APP_NAME}
export DATADOG_API_KEY=${DATADOG_API_KEY}
export DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
export DOMAIN=${APP_DOMAIN}
export INSTANCE_COUNT=${INSTANCE_COUNT}
export CF_STACK=${CF_STACK}

cd diegocanaryapp

./scripts/deploy
