#!/bin/bash

set -e -x -u

cd diegocanarywindowsapp

cf api ${API} --skip-ssl-validation

cf auth ${USER} ${PASSWORD}

cf create-org ${ORG}
cf target -o ${ORG}

cf create-space ${SPACE}
cf target -s ${SPACE}

cf push -s ${STACK_NAME} ${APP_NAME} -m 256M -k 64M -b hwc_buildpack -p ./${APP_PATH}
cf scale ${APP_NAME} -i ${INSTANCE_COUNT}

