#!/bin/bash

set -e -x -u

$(dirname $0)/bosh_setup
current_date=$(date)
director_version=$(bosh status | grep Version | tr -s ' ' | cut -f3 -d' ')

source $(dirname $0)/record_compatible_versions_from_$VERSION_SOURCE
new_row=$(generate_compatibility_row $ENVIRONMENT_NAME)

pushd diego-cf-compatibility
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  git remote add https $(git remote -v | grep origin | head -1 | awk '{ print $2 }'| sed 's/git@github.com:/https:\/\/github.com\//')
  git pull https master
  echo ${current_date},${RELEASE_STAGE},${director_version},${new_row} >> compatibility-v1.csv
  git add compatibility-v1.csv
  git commit -m "Add CF-Diego compatibility record on ${current_date} at release stage ${RELEASE_STAGE}"
popd

