#!/bin/bash

set -e -x -u

$(dirname $0)/bosh_setup
current_date=$(date)
director_version=$(bosh status | grep Version | tr -s ' ' | cut -f3 -d' ')

source $(dirname $0)/record_compatible_versions_from_$VERSION_SOURCE
new_row=$(generate_compatibility_row $ENVIRONMENT_NAME)

mkdir -p diego-cf-compatibility/tmp
cp runtime-credentials/diego-ci/ssh_keys/diego-cf-compatibility-push-pull diego-cf-compatibility/tmp/github
chmod 600 diego-cf-compatibility/tmp/github
export GIT_SSH=$(pwd)/diego-cf-compatibility/tmp/git_ssh.sh
echo "ssh -o StrictHostKeyChecking=no -i $(pwd)/diego-cf-compatibility/tmp/github" '"$@"' > $GIT_SSH
chmod +x $GIT_SSH

pushd diego-cf-compatibility
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  git pull --rebase origin master

  echo ${current_date},${RELEASE_STAGE},${director_version},${new_row} >> compatibility-v1.csv
  git add compatibility-v1.csv
  git commit -m "Add CF-Diego compatibility record on ${current_date} at release stage ${RELEASE_STAGE}"

  git push origin master
popd

