#!/bin/bash

generate_compatibility_row() {
  environment_name=$1

  stemcell_manifest=$(tar zxvOf bosh-stemcell/stemcell.tgz stemcell.MF 2>/dev/null)
  stemcell_name=$(echo "${stemcell_manifest}" | grep ^name | cut -f2 -d: | tr -d ' ')
  stemcell_version=$(echo "${stemcell_manifest}" | grep ^version | cut -f2 -d: | tr -d "'" | tr -d ' ')
  stemcell="${stemcell_name}/${stemcell_version}"

  cf_release_manifest=$(tar zxvOf cf-release-tarball/*.tgz ./release.MF 2>/dev/null)
  cf_release_sha=$(echo "${cf_release_manifest}" | grep ^commit_hash | cut -f2 -d: | tr -d "'" | tr -d ' ')

  diego_release_manifest=$(tar zxvOf diego-release-tarball/*.tgz ./release.MF 2>/dev/null)
  diego_release_version="N/A"
  if [ $environment_name == "a1" ]
  then
    diego_release_version=$(echo "${diego_release_manifest}" | grep ^version | cut -f2 -d: | tr -d "'" | tr -d ' ')
  fi
  diego_release_sha=$(echo "${diego_release_manifest}" | grep ^commit_hash | cut -f2 -d: | tr -d "'" | tr -d ' ')

  echo ${cf_release_sha},${stemcell},${diego_release_version},${diego_release_sha},${stemcell}
}
export -f generate_compatibility_row

