#!/bin/bash

set -e -x -u

generate_compatibility_row() {
  set -e
  environment_name=$1

  tmpdir=$(mktemp -d /tmp/compatibility.XXXXX)

  BOSH_URI="https://${BOSH_USER}:${BOSH_PASSWORD}@${BOSH_TARGET}"
  curl -o ${tmpdir}/deployments -s -k ${BOSH_URI}/deployments
  curl -o ${tmpdir}/releases -s -k ${BOSH_URI}/releases

  cf_data=$($(dirname $0)/extract-release-and-sha \
            ${tmpdir}/deployments \
            ${tmpdir}/releases \
            "cf-${environment_name} cf-${environment_name}-diego" \
            cf \
          )

  cf_data=$(echo $cf_data | cut -d',' -f2-)

  diego_data=$($(dirname $0)/extract-release-and-sha \
               ${tmpdir}/deployments \
               ${tmpdir}/releases \
               cf-${environment_name}-diego \
               diego \
             )

  garden_linux_data=$(
    $(dirname $0)/extract-release-and-sha \
      ${tmpdir}/deployments \
      ${tmpdir}/releases \
      cf-${environment_name}-diego \
      garden-linux \
  )
  garden_linux_data=$(echo $garden_linux_data | cut -d',' -f1)

  etcd_data=$(
    $(dirname $0)/extract-release-and-sha \
      ${tmpdir}/deployments \
      ${tmpdir}/releases \
      cf-${environment_name}-diego \
      etcd \
  )
  etcd_data=$(echo $etcd_data | cut -d',' -f1)

  echo ${cf_data},${diego_data},${garden_linux_data},${etcd_data}
}

$(dirname $0)/bosh_setup
current_date=$(date)
director_version=$(bosh status | grep Version | tr -s ' ' | cut -f3 -d' ')

new_row=$(generate_compatibility_row $ENVIRONMENT_NAME)

mkdir -p diego-cf-compatibility/tmp
cp runtime-credentials/diego-ci/ssh_keys/diego-cf-compatibility-push-pull diego-cf-compatibility/tmp/github
chmod 600 diego-cf-compatibility/tmp/github
export GIT_SSH=$(pwd)/diego-cf-compatibility/tmp/git_ssh.sh
echo "ssh -o StrictHostKeyChecking=no -i $(pwd)/diego-cf-compatibility/tmp/github" '"$@"' > $GIT_SSH
chmod +x $GIT_SSH

pushd diego-cf-compatibility
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  git checkout master
  git pull --rebase origin master

  echo ${current_date},${RELEASE_STAGE},${director_version},${new_row} >> compatibility-v2.csv
  git add compatibility-v2.csv
  git commit -m "Add CF-Diego-Garden compatibility record on ${current_date} at release stage ${RELEASE_STAGE}"

  git push origin master
popd
