#!/bin/bash

generate_compatibility_row() {
  environment_name=$1

  tmpdir=$(mktemp -d /tmp/compatibility.XXXXX)

  bosh deployments > ${tmpdir}/deployments
  bosh releases > ${tmpdir}/releases
  cf_data=$($(dirname $0)/extract-release-and-sha \
            ${tmpdir}/deployments \
            ${tmpdir}/releases \
            cf-${environment_name} \
            cf \
            | cut -d',' -f2- \
          )
  diego_data=$($(dirname $0)/extract-release-and-sha \
               ${tmpdir}/deployments \
               ${tmpdir}/releases \
               cf-${environment_name}-diego \
               diego \
             )
  echo ${cf_data},${diego_data}
}
export -f generate_compatibility_row

