#!/bin/bash

set -e -x -u

vizzini_manifest="${PWD}/${VIZZINI_MANIFEST}"

$(dirname $0)/bosh_setup

bosh deployment ${vizzini_manifest}

set +e
bosh run errand vizzini --keep-alive
errand_result=$?

exit $errand_result
