#!/bin/bash

set -e -x
source ~/.bashrc

setup_golang_dependencies() {
  pushd diego-release
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH
    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH
    go install github.com/onsi/ginkgo/ginkgo
  popd
}

setup_config() {
  cat > dusts_config.json <<EOF
{
  "bosh_director_url": "bosh.${DOMAIN}",
  "bosh_admin_user": "admin",
  "bosh_admin_password": "admin",
  "base_directory": "${PWD}",
  "v0_cf_release_path": "cf-stable-release",
  "v0_diego_release_path": "diego-stable-release",
  "v1_cf_release_path": "cf-release",
  "v1_diego_release_path": "diego-release",
  "override_domain": "${DOMAIN}",
  "max_polling_errors": ${MAX_POLLING_ERRORS},
  "aws_stubs_directory": "deployments-runtime/diego-ci/stubs/cf"
}
EOF

  export CONFIG=${PWD}/dusts_config.json
}

test_deploy_stable() {
  pushd diego-release/src/github.com/cloudfoundry-incubator/diego-upgrade-stability-tests
    ginkgo -v
  popd
}

main() {
  setup_golang_dependencies
  setup_config
  test_deploy_stable
}

main
