#!/bin/bash

set -e -x -u

$(dirname $0)/bosh_setup

bosh download manifest $(deployment_name) /tmp/$(deployment_name).yml

bosh deployment /tmp/${deployment_name}.yml

set +e
bosh run errand smoke_tests --download-logs --keep-alive
errand_result=$?
set -e

original_name=$(ls smoke_tests.0.*.tgz)
new_name=$(echo $original_name | sed 's/\.0\./\.0.0.0./')
mv $original_name smoke-test-results/$new_name
exit $errand_result
