#!/bin/bash

set -e -x
source ~/.bashrc
export GOPATH=`pwd`
export PATH=${PATH}:${GOPATH}/bin
DUSTS_PATH=${GOPATH}/src/github.com/cloudfoundry-incubator/diego-upgrade-stability-tests
OVERRIDE_DOMAIN=${BOSH_LITE_IP}.xip.io

setup_golang_dependencies() {
  mkdir -p ${DUSTS_PATH}
  mv diego-upgrade-stability-tests ${DUSTS_PATH}/..
  pushd ${DUSTS_PATH}
    set +e
    go get -t ./...
    go get github.com/onsi/ginkgo/ginkgo
    set -e
  popd
}

setup_config() {
  cat > dusts_config.json <<EOF
{
  "bosh_director_url": "${BOSH_LITE_IP}",
  "bosh_admin_user": "admin",
  "bosh_admin_password": "admin",
  "v0_cf_release_path": "${PWD}/cf-stable-release",
  "v0_diego_release_path": "${PWD}/diego-stable-release",
  "v1_cf_release_path": "${PWD}/cf-release",
  "v1_diego_release_path": "${PWD}/diego-release"
  "override_domain": "${OVERRIDE_DOMAIN}"
}
EOF

  export CONFIG=${PWD}/dusts_config.json
}

test_deploy_stable() {
  pushd ${DUSTS_PATH}
    ginkgo -v
  popd
}

main() {
  setup_golang_dependencies
  setup_config
  test_deploy_stable
}

main
