#!/usr/bin/env bash

set -ex

export BOSH_DEPLOYMENT
source ${PWD}/deployments-diego/${DEPLOYMENT_DIR}/.envrc

set +e
bosh run-errand ${ERRAND_NAME} --keep-alive --download-logs
errand_result=$?
set -e

original_name=$(ls ${ERRAND_NAME}-*.tgz)
new_name=$(echo $original_name | sed 's/-\([0-9]*-\)/.0.0.0.\1/')
mv $original_name errand-results/$new_name
exit $errand_result

