#!/bin/bash

set -e -x -u

manifest="${PWD}/${MANIFEST}"

$(dirname $0)/bosh_setup

# Report which cf-release and diego-release SHAs were deployed together
bosh deployments
bosh releases

bosh deployment ${manifest}

set +e
bosh run errand ${ERRAND} --download-logs --keep-alive
errand_result=$?
set -e

original_name=$(ls ${ERRAND}.0.*.tgz)
new_name=$(echo $original_name | sed 's/\.0\./\.0.0.0./')
mv $original_name errand-results/$new_name
exit $errand_result
