#!/bin/bash

set -e -x

source ~/.bashrc

log_in_to_bosh_lite() {
  export BOSH_TARGET=bosh.${DOMAIN}
  BOSH_USER=admin BOSH_PASSWORD=admin $(dirname $0)/bosh_setup
}

upload_releases() {
  bosh upload release $CF_RELEASE_V0
  bosh upload release $DIEGO_RELEASE_V0
  bosh upload release $GARDEN_LINUX_RELEASE_V0
  if [ -n "$ETCD_RELEASE_V0" ]; then
    bosh upload release $ETCD_RELEASE_V0
  fi

  bosh upload release $CF_RELEASE_VPRIME
  bosh upload release $DIEGO_RELEASE_VPRIME
  bosh upload release $GARDEN_LINUX_RELEASE_VPRIME
  bosh upload release $ETCD_RELEASE_VPRIME
  bosh upload release $ROOTFS_RELEASE_VPRIME

  if [ -n "$CF_MYSQL_RELEASE_VPRIME" ]; then
    bosh upload release $CF_MYSQL_RELEASE_VPRIME
  fi
}

upload_stemcell() {
  bosh upload stemcell $BOSH_STEMCELL --skip-if-exists
}

main() {
  log_in_to_bosh_lite
  upload_releases
  upload_stemcell
}

main
