#!/bin/bash

set -e -x

source ~/.bashrc

configure() {
  export BOSH_LITE_IP="$(cat provision-bosh-lite/bosh_lite_ip)"
}

log_in_to_bosh_lite() {
    # The bosh director may not yet be available
  for n in `seq 0 4`; do
    if bosh -n target $BOSH_LITE_IP; then
      bosh login admin admin
      return
    fi
    sleep 15
  done

  # The director was not reachable after 5 tries
  exit 1
}

upload_releases() {
  bosh upload release $CF_RELEASE
  bosh upload release $DIEGO_RELEASE
  bosh upload release $GARDEN_LINUX_RELEASE
}

upload_stemcell() {
  bosh upload stemcell $BOSH_STEMCELL
}

main() {
  configure
  log_in_to_bosh_lite
  upload_releases
  upload_stemcell
}

main
