#!/bin/bash

set -e -x

source ~/.bashrc

configure() {
  export BOSH_LITE_IP="$(cat provision-bosh-lite/bosh_lite_ip)"
}

log_in_to_bosh_lite() {
  set +e
  n=0
  while [ true ]
  do
    # The bosh director may not yet be available
    bosh -n target $BOSH_LITE_IP && break
    n=$[$n+1]
    if [ $n ge 5 ]
    then
      exit 1
    fi
    sleep 15
  done
  set -e
  bosh login admin admin
}

upload_releases() {
  bosh upload release $CF_RELEASE
  bosh upload release $DIEGO_RELEASE
  bosh upload release $GARDEN_LINUX_RELEASE
}

main() {
  configure
  log_in_to_bosh_lite
  upload_releases
}

main
