---
readme: |
  This task will start an arbitrary GCP instance.
oses:
  - linux
extra_inputs:
  bbl-state: (optional) bbl-state directory for determining instances to start/stop
params:
  INSTANCE_NAME: name of the GCP instance to start
  ZONE: name of the GCP availability zone the instance lives in
  PROJECT: GCP project name where the instance exists
  SERVICE_ACCOUNT_KEY: GCP service account key json
  BBL_STATE_DIR: name of the bbl state directory to try to find the instance name from. If specified, will start both jumpbox + bosh director
  RESUME: whether to resume a suspended vm instead of start a stopped one (set to 'true')
