---
platform: linux

inputs:
  - name: ci
  - name: repo
    optional: true
  - name: env
  - name: ci-config
    optional: true
  - name: release-01
    optional: true
  - name: release-02
    optional: true

params:
  ENVS:
  NAME:
  RUNTIME_CONFIG:
  TYPE:
  SKIP_DEFAULT_VAR_GENERATION:
  BBL_STATE_DIR:

run:
  path: ci/shared/tasks/bosh-update-config/task.bash
