---
platform: linux
image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: release

outputs:
- name: release-tarball

run:
  path: ci/garden-windows/tasks/bosh-cr/run

params:
  SKIP_TARBALL: "false"
