---
platform: linux

inputs:
- name: ci
- name: envoy-release

outputs:
- name: envoy-binary

run:
  path: ci/diego-release/tasks/create-envoy-blob/task.bash

params:
  GCP_KEY:
  IMAGE_NAME: envoyproxy/envoy-build-ubuntu
