---
readme: |
  This task will start an instance group
oses:
  - linux
params:
  DEPLOYMENT: Name of deployment
  INSTANCE_GROUP: Instance Group to be started
  BBL_STATE_DIR: name of bbl state dir (relative to the env resource)
