#!/usr/bin/env bash

set -ex

cp -r repo/. repo_with_commit
git config --global user.email "pivotal-netgarden-eng@pivotal.io"
git config --global user.name "Greenhouse CI"
git -C repo_with_commit add -A .

set +e
git -C repo_with_commit diff --quiet --exit-code --cached
if [[ $? == "0" ]]; then
  echo "No diff, nothing to commit"
  exit 0
fi
set -e

git -C repo_with_commit commit -m "$MESSAGE"

