---
platform: linux

inputs:
- name: tas-runtime
- name: ci

params:
  DEPLOYMENT: windows-gats
  GARDEN_PORT: 7777
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  JUMPBOX_IP:
  JUMPBOX_SSH_KEY:
run:
  path: ci/garden-windows/tasks/run-gats/task

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/tas-runtime-build
    tag: latest
