#!/usr/bin/env bash
set -e

source ci/garden-windows/bin/ci_helpers

eval "$(_bosh_socks5_env "${JUMPBOX_IP}" "${JUMPBOX_SSH_KEY}")"

bosh releases
bosh deployments
bosh -d "$DEPLOYMENT" run-errand gats

_close_ssh_connection
