---
platform: linux

inputs:
  - name: env
  - name: ci

outputs:
  - name: updated-env

params:
  SENTINEL_FILE: ~
  BBL_STATE_DIR: ~
  REASON: ~

run:
  path: ci/shared/tasks/write-env-sentinels/task.bash
