---
name: ((DEPLOYMENT_NAME))

releases:
- name: garden-runc
  url: ((DEPLOYMENT_GARDEN_RUNC_RELEASE_DIR))
  version: create
- name: winc
  url: ((DEPLOYMENT_WINC_RELEASE_DIR))
  version: create
- name: windows-utilities
  url: ((DEPLOYMENT_WINDOWS_UTILITIES_RELEASE_DIR))
  version: create
- name: garden-ci-artifacts
  url: ((DEPLOYMENT_GARDEN_CI_ARTIFACTS_RELEASE_DIR))
  version: create

stemcells:
- alias: windows
  os: ((WINDOWS_STEMCELL_OS))
  version: latest
- alias: stemcell
  os: ((CF_STEMCELL_OS))
  version: latest

instance_groups:
- name: gats
  instances: 1
  lifecycle: errand
  vm_type: ((CF_VM_TYPE))
  networks:
  - name: ((CF_NETWORK))
  azs: [((CF_AZ))]
  stemcell: stemcell
  jobs:
  - name: gats
    release: garden-runc
    properties:
      windows_rootfs: docker://mcr.microsoft.com/windows/nanoserver:ltsc2019
- name: garden-windows
  instances: 1
  vm_type: ((CF_VM_TYPE))
  vm_extensions:
    - 100GB_ephemeral_disk
  stemcell: windows
  azs: [((CF_AZ))]
  networks:
  - name: ((CF_NETWORK))
  jobs:
  - name: enable_ssh
    release: windows-utilities
  - name: garden-plugins
    release: garden-ci-artifacts
  - name: garden-windows
    release: garden-runc
    properties:
      garden:
        runtime_plugin: C:\var\vcap\packages\winc\winc.exe
        image_plugin: C:\var\vcap\packages\groot\groot.exe
        image_plugin_extra_args:
        - "--driver-store"
        - C:\var\vcap\data\groot
        network_plugin: C:\var\vcap\packages\noop_plugin\noop_plugin.exe
        nstar_bin: C:\var\vcap\packages\noop_plugin\noop_plugin.exe
        listen_address: 0.0.0.0:7777
        default_container_rootfs: docker://mcr.microsoft.com/windows/nanoserver:ltsc2019
        destroy_containers_on_start: true
  - name: winc
    release: winc
  - name: groot
    release: winc
    properties:
      groot:
        driver_store: C:\var\vcap\data\groot

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
